package sqlparse

import (
	"strings"
	"testing"

	"github.com/tucats/ego/internal/errors"
)

// mustRewrite parses sql as dialect, calls Rewrite (with lookup, which may
// be nil), and fails the test if either step errors. It returns the
// formatted result so callers can assert on the actual output text.
func mustRewrite(t *testing.T, sql string, dialect int, lookup UniqueKeyLookup) (string, []string) {
	t.Helper()

	p, err := New(sql, dialect)
	if err != nil {
		t.Fatalf("New: unexpected error: %v\nsql: %s", err, sql)
	}

	notes, err := p.Rewrite(lookup)
	if err != nil {
		t.Fatalf("Rewrite: unexpected error: %v\nsql: %s", err, sql)
	}

	return p.Format(), notes
}

func TestRewriteGeneratedKeySQLiteToPostgres(t *testing.T) {
	got, notes := mustRewrite(t, `CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT)`, PostgreSQL, nil)

	if !strings.Contains(got, "GENERATED BY DEFAULT AS IDENTITY") {
		t.Errorf("expected GENERATED BY DEFAULT AS IDENTITY in output, got:\n%s", got)
	}

	if strings.Contains(got, "AUTOINCREMENT") {
		t.Errorf("expected AUTOINCREMENT to be gone, got:\n%s", got)
	}

	if len(notes) == 0 {
		t.Errorf("expected at least one rewrite note")
	}

	// Round-trip: the rewritten PostgreSQL text must itself parse cleanly as
	// PostgreSQL and be a no-op under a second Rewrite pass.
	got2, notes2 := mustRewrite(t, got, PostgreSQL, nil)
	if got2 != got {
		t.Errorf("second Rewrite pass changed output:\n--- first ---\n%s\n--- second ---\n%s", got, got2)
	}

	if len(notes2) != 0 {
		t.Errorf("expected no notes on an already-PostgreSQL statement, got: %v", notes2)
	}
}

func TestRewriteGeneratedKeyPostgresToSQLite(t *testing.T) {
	for _, sql := range []string{
		`CREATE TABLE t (id SERIAL PRIMARY KEY, name TEXT)`,
		`CREATE TABLE t (id BIGSERIAL PRIMARY KEY, name TEXT)`,
		`CREATE TABLE t (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT)`,
		`CREATE TABLE t (id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name TEXT)`,
	} {
		got, _ := mustRewrite(t, sql, SQLite, nil)

		if !strings.Contains(got, "PRIMARY KEY AUTOINCREMENT") {
			t.Errorf("sql %q: expected PRIMARY KEY AUTOINCREMENT in output, got:\n%s", sql, got)
		}

		if !strings.Contains(got, "INTEGER") {
			t.Errorf("sql %q: expected INTEGER type in output, got:\n%s", sql, got)
		}

		if strings.Contains(got, "SERIAL") || strings.Contains(got, "IDENTITY") {
			t.Errorf("sql %q: expected no PostgreSQL-only syntax left, got:\n%s", sql, got)
		}
	}
}

func TestRewriteGeneratedKeyTableLevelPrimaryKey(t *testing.T) {
	// The PRIMARY KEY is written as a table-level constraint, not attached
	// to the column itself -- Rewrite must still find it, since sqlite3's
	// AUTOINCREMENT can only be expressed as a column-level constraint.
	got, notes := mustRewrite(t, `CREATE TABLE t (id SERIAL, name TEXT, PRIMARY KEY (id))`, SQLite, nil)

	if !strings.Contains(got, "AUTOINCREMENT") {
		t.Errorf("expected AUTOINCREMENT in output, got:\n%s", got)
	}

	if strings.Contains(got, "PRIMARY KEY (") {
		t.Errorf("expected the table-level PRIMARY KEY to be gone, got:\n%s", got)
	}

	found := false

	for _, n := range notes {
		if strings.Contains(n, "table level to column level") {
			found = true
		}
	}

	if !found {
		t.Errorf("expected a note about moving the PRIMARY KEY, got: %v", notes)
	}
}

func TestRewriteGeneratedKeyWithoutPrimaryKeyErrorsTowardSQLite(t *testing.T) {
	// PostgreSQL allows a GENERATED ... AS IDENTITY column that is not the
	// table's PRIMARY KEY; sqlite3 has no way to express that.
	p, err := New(`CREATE TABLE t (id INTEGER GENERATED ALWAYS AS IDENTITY, other_id INTEGER PRIMARY KEY)`, SQLite)
	if err != nil {
		t.Fatalf("New: unexpected error: %v", err)
	}

	_, err = p.Rewrite(nil)
	if err == nil {
		t.Fatalf("expected an error, got none")
	}

	ee, ok := err.(*errors.Error)
	if !ok {
		t.Fatalf("expected *errors.Error, got %T", err)
	}

	if !ee.Equal(errors.ErrSQLDialectRewrite) {
		t.Errorf("got error %v, want ErrSQLDialectRewrite", err)
	}
}

func TestRewriteCompositePrimaryKeyErrorsTowardSQLite(t *testing.T) {
	p, err := New(`CREATE TABLE t (id SERIAL, other TEXT, PRIMARY KEY (id, other))`, SQLite)
	if err != nil {
		t.Fatalf("New: unexpected error: %v", err)
	}

	_, err = p.Rewrite(nil)
	if err == nil {
		t.Fatalf("expected an error for a composite primary key, got none")
	}
}

func TestRewriteWithoutRowIDDroppedForPostgres(t *testing.T) {
	got, notes := mustRewrite(t, `CREATE TABLE t (id INTEGER PRIMARY KEY) WITHOUT ROWID`, PostgreSQL, nil)

	if strings.Contains(got, "WITHOUT ROWID") {
		t.Errorf("expected WITHOUT ROWID to be dropped, got:\n%s", got)
	}

	found := false

	for _, n := range notes {
		if strings.Contains(n, "WITHOUT ROWID") {
			found = true
		}
	}

	if !found {
		t.Errorf("expected a note about dropping WITHOUT ROWID, got: %v", notes)
	}
}

func TestRewriteAlterTableAddColumn(t *testing.T) {
	got, _ := mustRewrite(t, `ALTER TABLE t ADD COLUMN id SERIAL PRIMARY KEY`, SQLite, nil)

	if !strings.Contains(got, "AUTOINCREMENT") || !strings.Contains(got, "PRIMARY KEY") {
		t.Errorf("expected a promoted PRIMARY KEY AUTOINCREMENT, got:\n%s", got)
	}
}

func TestRewriteInsertOrIgnoreToPostgres(t *testing.T) {
	got, notes := mustRewrite(t, `INSERT OR IGNORE INTO t (id, name) VALUES (1, 'a')`, PostgreSQL, nil)

	if !strings.Contains(got, "ON CONFLICT") || !strings.Contains(got, "DO NOTHING") {
		t.Errorf("expected ON CONFLICT DO NOTHING, got:\n%s", got)
	}

	if strings.Contains(got, "OR IGNORE") {
		t.Errorf("expected OR IGNORE to be gone, got:\n%s", got)
	}

	if len(notes) == 0 {
		t.Errorf("expected a rewrite note")
	}
}

func TestRewriteInsertOrAbortToPostgres(t *testing.T) {
	got, notes := mustRewrite(t, `INSERT OR ABORT INTO t (id, name) VALUES (1, 'a')`, PostgreSQL, nil)

	if strings.Contains(got, "OR ABORT") || strings.Contains(got, "ON CONFLICT") {
		t.Errorf("expected OR ABORT simply dropped, got:\n%s", got)
	}

	if len(notes) == 0 {
		t.Errorf("expected a rewrite note explaining the drop")
	}
}

func TestRewriteInsertOrFailAndRollbackError(t *testing.T) {
	for _, action := range []string{"FAIL", "ROLLBACK"} {
		p, err := New(`INSERT OR `+action+` INTO t (id) VALUES (1)`, PostgreSQL)
		if err != nil {
			t.Fatalf("New: unexpected error: %v", err)
		}

		if _, err := p.Rewrite(nil); err == nil {
			t.Errorf("action %s: expected an error, got none", action)
		}
	}
}

func TestRewriteInsertOrReplaceToPostgres(t *testing.T) {
	lookup := func(table string) ([]string, error) {
		if table != "t" {
			t.Fatalf("unexpected table passed to lookup: %q", table)
		}

		return []string{"id"}, nil
	}

	got, notes := mustRewrite(t, `INSERT OR REPLACE INTO t (id, name, email) VALUES (1, 'a', 'a@example.com')`, PostgreSQL, lookup)

	if !strings.Contains(got, "ON CONFLICT (") || !strings.Contains(got, "\"id\"") {
		t.Errorf("expected ON CONFLICT (\"id\"), got:\n%s", got)
	}

	if !strings.Contains(got, "DO UPDATE SET") {
		t.Errorf("expected DO UPDATE SET, got:\n%s", got)
	}

	if !strings.Contains(got, "excluded") {
		t.Errorf("expected a reference to the excluded pseudo-table, got:\n%s", got)
	}

	if strings.Contains(got, `"EXCLUDED"`) {
		t.Errorf("expected the excluded pseudo-table reference to be lower-case (so PostgreSQL quoting still resolves it), got:\n%s", got)
	}

	if strings.Contains(got, "\"id\" = ") {
		t.Errorf("expected the key column not to appear in the SET list, got:\n%s", got)
	}

	if len(notes) == 0 {
		t.Errorf("expected a rewrite note")
	}
}

func TestRewriteInsertOrReplaceWithoutColumnListErrors(t *testing.T) {
	p, err := New(`INSERT OR REPLACE INTO t VALUES (1, 'a')`, PostgreSQL)
	if err != nil {
		t.Fatalf("New: unexpected error: %v", err)
	}

	if _, err := p.Rewrite(func(string) ([]string, error) { return []string{"id"}, nil }); err == nil {
		t.Fatalf("expected an error for a missing column list, got none")
	}
}

func TestRewriteInsertOrReplaceWithoutLookupErrors(t *testing.T) {
	p, err := New(`INSERT OR REPLACE INTO t (id, name) VALUES (1, 'a')`, PostgreSQL)
	if err != nil {
		t.Fatalf("New: unexpected error: %v", err)
	}

	if _, err := p.Rewrite(nil); err == nil {
		t.Fatalf("expected an error when no UniqueKeyLookup is supplied, got none")
	}
}

func TestRewriteInsertOnConflictUnchangedOnBothDialects(t *testing.T) {
	// PostgreSQL-style ON CONFLICT is already valid sqlite3 (3.24+); Rewrite
	// must leave it alone in both directions.
	sql := `INSERT INTO t (id, name) VALUES (1, 'a') ON CONFLICT (id) DO UPDATE SET name = excluded.name`

	for _, dialect := range []int{SQLite, PostgreSQL} {
		got, notes := mustRewrite(t, sql, dialect, nil)

		if len(notes) != 0 {
			t.Errorf("dialect %d: expected no rewrite notes for already-native ON CONFLICT, got: %v", dialect, notes)
		}

		if !strings.Contains(got, "ON CONFLICT") {
			t.Errorf("dialect %d: expected ON CONFLICT preserved, got:\n%s", dialect, got)
		}
	}
}
