// Package rshandlers implements the HTTP endpoints for Ego's OAuth2 Resource
// Server (RS) role.  It provides three handlers:
//
//   - CallbackHandler         — /services/admin/oauth/callback
//   - AuthorizeRedirectHandler — /services/admin/oauth/authorize
//   - ConfigHandler           — /services/admin/oauth/config
//
// This package is kept separate from server/oauth so that server/oauth (which
// contains the JWT validation logic imported by the router) does not import the
// router package — avoiding a circular dependency.
package rshandlers

import (
	"encoding/json"
	"net/http"

	"github.com/tucats/ego/app-cli/settings"
	"github.com/tucats/ego/app-cli/ui"
	"github.com/tucats/ego/defs"
	"github.com/tucats/ego/router"
	"github.com/tucats/ego/server/oauth"
	"github.com/tucats/ego/tokens"
	"github.com/tucats/ego/util"
)

// callbackResponse is the JSON body returned from /services/admin/oauth/callback
// in resource-server mode, when the client needs the raw JWT access token.
type callbackResponse struct {
	// AccessToken is the JWT returned by the IdP.
	AccessToken string `json:"access_token"`

	// TokenType is always "Bearer".
	TokenType string `json:"token_type"`
}

// CallbackHandler processes GET /services/admin/oauth/callback.
//
// This endpoint is the redirect target registered with the identity provider.
// After the user authenticates with the IdP, the browser is sent here with:
//
//	code  — the short-lived authorization code to exchange for a JWT.
//	state — the opaque PKCE state token generated by AuthorizeRedirectHandler;
//	        must match the stored state to prevent CSRF attacks.
//
// If the IdP encountered an error, it passes "error" and optionally
// "error_description" instead of "code".
//
// Behavior depends on the configured mode (ego.server.oauth.mode):
//   - proxy / hybrid:         Exchange code, validate JWT, issue a native Ego
//     token and return it as {"access_token": "...", "token_type": "Bearer"}.
//   - resource-server:        Exchange code, return the raw JWT access token.
func CallbackHandler(session *router.Session, w http.ResponseWriter, r *http.Request) int {
	// If the IdP signaled an error, report it and stop.
	if idpError := r.URL.Query().Get("error"); idpError != "" {
		desc := r.URL.Query().Get("error_description")

		ui.Log(ui.AuthLogger, "oauth.rs.callback.idp.error", ui.A{
			"session": session.ID,
			"error":   idpError,
			"desc":    desc,
		})

		return util.ErrorResponse(w, session.ID,
			"IdP authorization error: "+idpError+": "+desc,
			http.StatusBadRequest)
	}

	// Validate the state parameter to prevent CSRF.
	state := r.URL.Query().Get("state")
	if state == "" {
		return util.ErrorResponse(w, session.ID,
			"missing state parameter in OAuth2 callback", http.StatusBadRequest)
	}

	ps, err := oauth.ValidateCallbackState(state)
	if err != nil {
		ui.Log(ui.AuthLogger, "oauth.rs.callback.bad.state", ui.A{
			"session": session.ID,
			"error":   err.Error(),
		})

		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusBadRequest)
	}

	// Extract the authorization code.
	code := r.URL.Query().Get("code")
	if code == "" {
		return util.ErrorResponse(w, session.ID,
			"missing code parameter in OAuth2 callback", http.StatusBadRequest)
	}

	// Exchange the code for tokens.
	cfg := oauth.GetConfig()

	accessToken, _, err := oauth.ExchangeCodePublic(cfg, code, ps.CodeVerifier)
	if err != nil {
		ui.Log(ui.AuthLogger, "oauth.rs.callback.exchange.failed", ui.A{
			"session": session.ID,
			"error":   err.Error(),
		})

		return util.ErrorResponse(w, session.ID,
			"token exchange failed: "+err.Error(), http.StatusBadGateway)
	}

	// Validate the received JWT to extract the user identity and permissions.
	user, permissions, err := oauth.ValidateJWT(session.ID, accessToken)
	if err != nil {
		return util.ErrorResponse(w, session.ID,
			"received JWT is invalid: "+err.Error(), http.StatusBadGateway)
	}

	ui.Log(ui.AuthLogger, "oauth.rs.callback.ok", ui.A{
		"session": session.ID,
		"user":    user,
		"mode":    cfg.Mode,
	})

	// In proxy and hybrid modes issue a native Ego token; in resource-server
	// mode return the raw JWT.
	if cfg.Mode == oauth.ModeProxy || cfg.Mode == oauth.ModeHybrid {
		egoToken, err := tokens.New(
			user,
			permissionsToData(permissions),
			settings.Get(defs.ServerTokenExpirationSetting),
			defs.InstanceID,
			session.ID,
		)
		if err != nil {
			return util.ErrorResponse(w, session.ID,
				"failed to issue Ego token: "+err.Error(),
				http.StatusInternalServerError)
		}

		payload := map[string]string{
			"access_token": egoToken,
			"token_type":   "Bearer",
			"user":         user,
		}

		w.Header().Set("Content-Type", defs.JSONMediaType)
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(payload)

		return http.StatusOK
	}

	// resource-server mode: return the JWT.
	resp := callbackResponse{
		AccessToken: accessToken,
		TokenType:   "Bearer",
	}

	w.Header().Set("Content-Type", defs.JSONMediaType)
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(resp)

	return http.StatusOK
}

// permissionsToData formats a permission slice as a comma-separated string for
// storage in a token's Data field.
func permissionsToData(permissions []string) string {
	result := ""

	for i, p := range permissions {
		if i > 0 {
			result += ","
		}

		result += p
	}

	return result
}
