// # WebAuthn / Passkey Authentication
// (Or, My Extended and Confusing Journey)
//
// ## What is a passkey?
//
// A passkey is a way to log in without a password. Instead of a shared secret
// (a password) that both the user and server know, a passkey uses public-key
// cryptography: the user's device (phone, laptop, hardware key) holds a private
// key that never leaves it, and the server stores only the matching public key.
// To log in, the device signs a one-time challenge from the server using the
// private key. The server verifies the signature with the public key it already
// has. Because the private key never travels over the network, there is nothing
// useful to steal by intercepting the login traffic.
//
// Passkeys are surfaced to the user as "Touch ID", "Face ID", Windows Hello,
// or a hardware security key. The user sees a biometric prompt or a PIN entry —
// the cryptographic details are handled automatically by the operating system.
//
// The technical standard that defines how this exchange works is called WebAuthn
// (Web Authentication API). It is part of the larger FIDO2 specification.
//
// ## Key concepts
//
// RPID (Relying Party ID)
//   The domain name that "owns" the passkey, e.g. "example.com". Browsers and
//   operating systems tie a passkey to its RPID so that a credential registered
//   for example.com cannot be used to log in to evil.com. If the ego.server.
//   webauthn.rpid setting is not configured, the server derives it from the Host
//   header of each incoming request (fine for development, not recommended for
//   production).
//
// Challenge (nonce)
//   A random one-time value generated by the server at the start of each login
//   or registration attempt. The device must sign this exact value. Because it
//   is random and single-use, an attacker cannot replay a captured signature.
//
// Credential / credential ID
//   A passkey registered with the server. Each credential has a unique ID, a
//   public key, and a sign counter. One user account can hold multiple
//   credentials (one per device).
//
// Sign counter
//   A number stored by both the authenticator (device) and the server. Every
//   time the passkey is used to sign, the device increments the counter and
//   includes the new value in the response. If the server sees a counter value
//   that is not higher than the one it stored, the credential may have been
//   cloned — copied from one device to another. This server rejects such logins.
//
// User handle
//   The server-side user identifier embedded in a discoverable passkey. It is
//   the binary form of the user's UUID. During a login the authenticator returns
//   this handle so the server can find the right user record without the user
//   having to type their username first.
//
// Discoverable login
//   A login flow where the user does not type a username. The browser or OS
//   presents a list of passkeys that are already registered for this site and
//   the user simply picks one (or it is chosen automatically). All passkey logins
//   in this server use the discoverable flow.
//
// ## How a passkey login works (the "authentication ceremony")
//
// Step 1 — Begin (POST /services/admin/webauthn/login/begin)
//   The server generates a random challenge, wraps it in WebAuthn session data,
//   stores the session data in an in-memory cache keyed by a UUID nonce, and
//   returns:
//     • The challenge options as a JSON blob that the browser passes to the
//       WebAuthn API (navigator.credentials.get).
//     • An HttpOnly cookie containing the nonce so the finish step can find the
//       right session data.
//
// Step 2 — Browser interaction (handled entirely by the browser / OS)
//   The browser calls the platform authenticator (Touch ID, Face ID, etc.) and
//   asks it to sign the challenge using the passkey stored for this RPID. The
//   authenticator returns a signed assertion that includes the credential ID,
//   the user handle, the updated sign counter, and the signature.
//
// Step 3 — Finish (POST /services/admin/webauthn/login/finish)
//   The browser posts the signed assertion to the server. The server:
//     a. Reads the nonce from the cookie and fetches the matching session data
//        from the cache (consuming it so it cannot be reused).
//     b. Calls the WebAuthn library to verify the signature against the stored
//        public key, check the challenge matches, and validate the RPID.
//     c. Uses the user handle in the assertion to locate the user record.
//     d. Checks that the sign counter advanced (clone detection).
//     e. Verifies the user has logon permission.
//     f. Updates the stored sign counter for the credential.
//     g. Mints a bearer token and returns a LogonResponse identical to the one
//        produced by a normal password login.
//
// ## How registering a new passkey works (the "registration ceremony")
//
// Registration is very similar but requires an already-authenticated user (a
// valid bearer token must be present on the request). The steps mirror login:
//
// Step 1 — Begin (POST /services/admin/webauthn/register/begin)
//   The server generates registration options (challenge + RPID + user info)
//   and returns them to the browser, storing the session data behind a nonce
//   cookie as above.
//
// Step 2 — Browser interaction
//   The browser invokes the platform authenticator (navigator.credentials.create)
//   which generates a new key pair, stores the private key in the secure enclave
//   or hardware key, and returns the public key and an attestation to the browser.
//
// Step 3 — Finish (POST /services/admin/webauthn/register/finish)
//   The browser posts the new credential to the server. The server verifies the
//   attestation, appends the new credential (public key + credential ID + initial
//   sign counter) to the user record, and persists the updated record.
//
// ## Configuration
//
// ego.server.allow.passkeys (bool, default false)
//   Master switch. All ceremony endpoints return 404 when this is false.
//
// ego.server.webauthn.rpid (string, default "")
//   The Relying Party domain. Should be set to the bare domain name of the server
//   (e.g. "example.com") for production deployments. If empty, the RPID is
//   derived from the Host header at request time.
//
// ## Security notes
//
// • The challenge cookie is marked HttpOnly (not readable by JavaScript) and
//   SameSite: Strict (not sent on cross-site requests). The Secure flag is set
//   when the connection is TLS or X-Forwarded-Proto: https.
// • Begin endpoints are rate-limited to 10 requests per IP per minute and the
//   number of pending (unfinished) ceremonies is capped at 200 globally to
//   prevent cache-exhaustion attacks.
// • Logins are rejected when the authenticator's clone-warning flag is set.
// • Administrator passkey deletions are logged at SERVER level so they appear
//   in the dashboard and cannot be silently hidden.

package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/go-webauthn/webauthn/webauthn"
	"github.com/google/uuid"
	"github.com/tucats/ego/app-cli/settings"
	"github.com/tucats/ego/app-cli/ui"
	"github.com/tucats/ego/builtins"
	"github.com/tucats/ego/caches"
	"github.com/tucats/ego/data"
	"github.com/tucats/ego/defs"
	"github.com/tucats/ego/egostrings"
	"github.com/tucats/ego/errors"
	"github.com/tucats/ego/runtime/cipher"
	auth "github.com/tucats/ego/server/auth"
	"github.com/tucats/ego/symbols"
	"github.com/tucats/ego/tokens"
	"github.com/tucats/ego/util"
)

const webAuthnChallengeCookie = "webauthn_challenge"

// ── helpers ───────────────────────────────────────────────────────────────────

// webAuthnInstance returns a configured *webauthn.WebAuthn or writes a 500
// response and returns nil on error. The RPID and allowed origin are derived
// from r when ego.server.webauthn.rpid is not explicitly configured, enabling
// zero-config local development with Apple passkeys.
func webAuthnInstance(w http.ResponseWriter, r *http.Request, sessionID int) *webauthn.WebAuthn {
	wau, err := auth.NewWebAuthnForRequest(r)
	if err != nil {
		msg := fmt.Sprintf("WebAuthn not available: %v", err)
		ui.Log(ui.AuthLogger, "auth.webauthn.config.error", ui.A{
			"session": sessionID,
			"error":   err})
		http.Error(w, msg, http.StatusInternalServerError)

		return nil
	}

	return wau
}

// challengeCookie returns a short-lived HttpOnly cookie carrying a session nonce.
// secure should be true when the connection is HTTPS so that browsers enforce
// the Secure attribute; pass false only for plain-HTTP local development.
func challengeCookie(nonce string, maxAge int, secure bool) *http.Cookie {
	return &http.Cookie{
		Name:     webAuthnChallengeCookie,
		Value:    nonce,
		Path:     "/",
		MaxAge:   maxAge,
		HttpOnly: true,
		SameSite: http.SameSiteStrictMode,
		Secure:   secure,
	}
}

// isSecureRequest returns true when the incoming request arrived over TLS or
// was forwarded from an HTTPS front-end (X-Forwarded-Proto: https).
func isSecureRequest(r *http.Request) bool {
	return r.TLS != nil || strings.EqualFold(r.Header.Get("X-Forwarded-Proto"), "https")
}

// storeChallenge stores webauthn SessionData in the challenge cache keyed by
// the supplied nonce UUID and returns the nonce string.
func storeChallenge(sessionData *webauthn.SessionData) (string, error) {
	nonce := uuid.New().String()

	b, err := json.Marshal(sessionData)
	if err != nil {
		return "", err
	}

	caches.Add(caches.WebAuthnChallengeCache, nonce, b)

	return nonce, nil
}

// loadChallenge retrieves and removes SessionData from the challenge cache using
// the nonce stored in the request cookie.
func loadChallenge(r *http.Request) (*webauthn.SessionData, error) {
	cookie, err := r.Cookie(webAuthnChallengeCookie)
	if err != nil {
		return nil, fmt.Errorf("missing %s cookie", webAuthnChallengeCookie)
	}

	nonce := cookie.Value

	v, found := caches.Find(caches.WebAuthnChallengeCache, nonce)
	if !found {
		return nil, fmt.Errorf("WebAuthn session expired or not found")
	}

	caches.Delete(caches.WebAuthnChallengeCache, nonce)

	b, ok := v.([]byte)
	if !ok {
		return nil, fmt.Errorf("invalid session data type in cache")
	}

	var sd webauthn.SessionData

	if err := json.Unmarshal(b, &sd); err != nil {
		return nil, err
	}

	return &sd, nil
}

// issueToken mints a bearer token for the named user and writes a LogonResponse.
// This mirrors the logic in LogonHandler so both paths produce identical responses.
func issueToken(w http.ResponseWriter, session *Session, username string) int {
	s := symbols.NewRootSymbolTable("webauthn logon")
	s.SetAlways("cipher", cipher.CipherPackage)
	s.SetAlways(defs.SessionVariable, session.ID)

	v, err := builtins.CallBuiltin(s, "cipher.New", username, "", "")
	if err != nil {
		ui.Log(ui.AuthLogger, "auth.error", ui.A{
			"session": session.ID,
			"error":   err})

		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	tokenStr, ok := v.(string)
	if !ok {
		msg := fmt.Sprintf("invalid internal token data type: %s", data.TypeOf(v).String())
		ui.Log(ui.AuthLogger, "auth.error", ui.A{
			"session": session.ID,
			"error":   msg})

		return util.ErrorResponse(w, session.ID, msg, http.StatusInternalServerError)
	}

	serverDurationString := settings.Get(defs.ServerTokenExpirationSetting)
	if serverDurationString == "" {
		serverDurationString = "15m"
		settings.SetDefault(defs.ServerTokenExpirationSetting, serverDurationString)
	}

	duration, _ := util.ParseDuration(serverDurationString)

	perms := auth.GetPermissions(session.ID, username)
	isAdmin := util.InListInsensitive(defs.RootPermission, perms...)
	canCode := isAdmin || util.InList(defs.CodeRunPermission, perms...)

	response := defs.LogonResponse{
		Identity: username,
		RestStatusResponse: defs.RestStatusResponse{
			ServerInfo: util.MakeServerInfo(session.ID),
			Status:     http.StatusOK,
		},
		Token:      tokenStr,
		Expiration: time.Now().Add(duration).Format(time.UnixDate),
		CanAdmin:   isAdmin,
		CanCode:    canCode,
	}

	if t, err := tokens.Unwrap(tokenStr, 0); err == nil {
		response.ID = t.TokenID.String()
	}

	w.Header().Add(defs.ContentTypeHeader, defs.LogonMediaType)

	_ = util.WriteJSON(w, response, &session.ResponseLength)

	if ui.IsActive(ui.RestLogger) {
		response.Token = egostrings.TruncateMiddle(tokenStr, 10)

		b, _ := json.MarshalIndent(response, ui.JSONIndentPrefix, ui.JSONIndentSpacer)
		ui.WriteLog(ui.RestLogger, "rest.response.payload", ui.A{
			"session": session.ID,
			"body":    string(b)})
	}

	return http.StatusOK
}

// findUserByHandle searches all users for the one whose UUID matches the bytes
// in userHandle (the value returned by webAuthnUser.WebAuthnID).
func findUserByHandle(sessionID int, userHandle []byte) (defs.User, error) {
	for _, u := range auth.AuthService.ListUsers(false) {
		b, _ := u.ID.MarshalBinary()
		if strings.EqualFold(fmt.Sprintf("%x", b), fmt.Sprintf("%x", userHandle)) {
			ui.Log(ui.AuthLogger, "auth.webauth.found.by.handle", ui.A{
				"session": sessionID,
				"user":    u.Name,
			})

			return u, nil
		}
	}

	ui.Log(ui.AuthLogger, "auth.webauth.not.found.by.handle", ui.A{
		"session": sessionID,
	})

	return defs.User{}, errors.ErrNoSuchUser
}

// ── handlers ──────────────────────────────────────────────────────────────────

// WebAuthnConfigHandler returns the server's passkey feature flag.
// GET /services/admin/webauthn/config — no authentication required.
func WebAuthnConfigHandler(session *Session, w http.ResponseWriter, r *http.Request) int {
	enabled := settings.GetBool(defs.WebAuthnAllowPasskeysSetting)

	w.Header().Set(defs.ContentTypeHeader, defs.JSONMediaType)

	resp := struct {
		Server   defs.ServerInfo `json:"server"`
		Msg      string          `json:"msg"`
		Status   int             `json:"status"`
		Passkeys bool            `json:"passkeys"`
	}{
		Server:   util.MakeServerInfo(session.ID),
		Passkeys: enabled,
		Status:   200,
		Msg:      "",
	}

	b, _ := json.Marshal(resp)
	_, _ = w.Write(b)
	session.ResponseLength += len(b)

	return http.StatusOK
}

// passkeyGuard returns a non-zero status code and writes a 404 response when
// the ego.server.allow.passkeys setting is false. Handlers call this first so
// that the ceremony endpoints are unreachable regardless of UI state.
func passkeyGuard(w http.ResponseWriter, session *Session) int {
	if !settings.GetBool(defs.WebAuthnAllowPasskeysSetting) {
		ui.Log(ui.AuthLogger, "auth.webauthn.disabled", ui.A{
			"session": session.ID})

		return util.ErrorResponse(w, session.ID, "passkeys not enabled", http.StatusNotFound)
	}

	return 0
}

// WebAuthnLoginBeginHandler starts the passkey authentication ceremony.
// POST /services/admin/webauthn/login/begin — no credentials required.
func WebAuthnLoginBeginHandler(session *Session, w http.ResponseWriter, r *http.Request) int {
	if status := passkeyGuard(w, session); status != 0 {
		return status
	}

	if status := webAuthnBeginGuard(w, session, r); status != 0 {
		return status
	}

	wau := webAuthnInstance(w, r, session.ID)
	if wau == nil {
		return http.StatusNotImplemented
	}

	options, sessionData, err := wau.BeginDiscoverableLogin()
	if err != nil {
		ui.Log(ui.AuthLogger, "auth.webauthn.begin.error", ui.A{
			"session": session.ID,
			"error":   err})

		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	nonce, err := storeChallenge(sessionData)
	if err != nil {
		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	http.SetCookie(w, challengeCookie(nonce, 300, isSecureRequest(r)))

	ui.Log(ui.AuthLogger, "auth.webauthn.login.begin", ui.A{
		"session": session.ID})

	w.Header().Set(defs.ContentTypeHeader, defs.JSONMediaType)

	b, _ := json.Marshal(options)
	_, _ = w.Write(b)
	session.ResponseLength += len(b)

	return http.StatusOK
}

// WebAuthnLoginFinishHandler completes the passkey authentication ceremony and
// issues a bearer token on success.
// POST /services/admin/webauthn/login/finish — no credentials required.
func WebAuthnLoginFinishHandler(session *Session, w http.ResponseWriter, r *http.Request) int {
	if status := passkeyGuard(w, session); status != 0 {
		return status
	}

	wau := webAuthnInstance(w, r, session.ID)
	if wau == nil {
		return http.StatusNotImplemented
	}

	sessionData, err := loadChallenge(r)
	if err != nil {
		ui.Log(ui.AuthLogger, "auth.webauthn.session.error", ui.A{
			"session": session.ID,
			"error":   err})

		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusBadRequest)
	}

	// Clear the challenge cookie regardless of outcome.
	http.SetCookie(w, challengeCookie("", -1, isSecureRequest(r)))

	// userHandler is called by the library to resolve the user from the credential.
	var foundUser defs.User

	userHandler := func(rawID, userHandle []byte) (webauthn.User, error) {
		u, err := findUserByHandle(session.ID, userHandle)
		if err != nil {
			return nil, err
		}

		foundUser = u

		return auth.WebAuthnUserFrom(u), nil
	}

	credential, err := wau.FinishDiscoverableLogin(userHandler, *sessionData, r)
	if err != nil {
		ui.Log(ui.AuthLogger, "auth.webauthn.login.fail", ui.A{
			"session": session.ID,
			"error":   err})

		return util.ErrorResponse(w, session.ID, "passkey verification failed", http.StatusUnauthorized)
	}

	// Reject logins where the authenticator sign counter did not advance — a
	// strong indicator that the credential has been cloned.
	if credential.Authenticator.CloneWarning {
		ui.Log(ui.AuthLogger, "auth.webauthn.clone.warning", ui.A{
			"session": session.ID,
			"user":    foundUser.Name})

		return util.ErrorResponse(w, session.ID, "passkey verification failed", http.StatusUnauthorized)
	}

	// Verify the user has permission to log in.
	if auth.FindPermission(foundUser, defs.RootPermission) < 0 &&
		auth.FindPermission(foundUser, defs.LogonPermission) < 0 {
		ui.Log(ui.AuthLogger, "auth.webauthn.no.permission", ui.A{
			"session": session.ID,
			"user":    foundUser.Name})

		return util.ErrorResponse(w, session.ID, "account not permitted to log in", http.StatusForbidden)
	}

	// Persist the updated sign counter back to the user record.
	if err := updatePasskeyCounter(session.ID, foundUser, credential); err != nil {
		// Non-fatal: log and continue.
		ui.Log(ui.AuthLogger, "auth.webauthn.counter.error", ui.A{
			"session": session.ID,
			"error":   err})
	}

	ui.Log(ui.AuthLogger, "auth.webauthn.login.ok", ui.A{
		"session": session.ID,
		"user":    foundUser.Name})

	return issueToken(w, session, foundUser.Name)
}

// WebAuthnRegisterBeginHandler starts the passkey registration ceremony for an
// already-authenticated user.
// POST /services/admin/webauthn/register/begin — Bearer token required.
func WebAuthnRegisterBeginHandler(session *Session, w http.ResponseWriter, r *http.Request) int {
	if status := passkeyGuard(w, session); status != 0 {
		return status
	}

	if status := webAuthnBeginGuard(w, session, r); status != 0 {
		return status
	}

	wau := webAuthnInstance(w, r, session.ID)
	if wau == nil {
		return http.StatusNotImplemented
	}

	u, err := auth.AuthService.ReadUser(session.ID, session.User, false)
	if err != nil {
		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	options, sessionData, err := wau.BeginRegistration(auth.WebAuthnUserFrom(u))
	if err != nil {
		ui.Log(ui.AuthLogger, "auth.webauthn.begin.error", ui.A{
			"session": session.ID,
			"error":   err})

		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	nonce, err := storeChallenge(sessionData)
	if err != nil {
		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	http.SetCookie(w, challengeCookie(nonce, 300, isSecureRequest(r)))

	ui.Log(ui.AuthLogger, "auth.webauthn.register.begin", ui.A{
		"session": session.ID,
		"user":    session.User})

	w.Header().Set(defs.ContentTypeHeader, defs.JSONMediaType)

	b := util.WriteJSON(w, options, &session.ResponseLength)
	ui.Log(ui.AuthLogger, "auth.webauth.options", ui.A{
		"session": session.ID,
		"body":    string(b),
	})

	return http.StatusOK
}

// WebAuthnRegisterFinishHandler completes the passkey registration ceremony and
// appends the new credential to the user record.
// POST /services/admin/webauthn/register/finish — Bearer token required.
func WebAuthnRegisterFinishHandler(session *Session, w http.ResponseWriter, r *http.Request) int {
	if status := passkeyGuard(w, session); status != 0 {
		return status
	}

	wau := webAuthnInstance(w, r, session.ID)
	if wau == nil {
		return http.StatusNotImplemented
	}

	u, err := auth.AuthService.ReadUser(session.ID, session.User, false)
	if err != nil {
		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	sessionData, err := loadChallenge(r)
	if err != nil {
		ui.Log(ui.AuthLogger, "auth.webauthn.session.error", ui.A{
			"session": session.ID,
			"error":   err})

		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusBadRequest)
	}

	// Clear the challenge cookie regardless of outcome.
	http.SetCookie(w, challengeCookie("", -1, isSecureRequest(r)))

	credential, err := wau.FinishRegistration(auth.WebAuthnUserFrom(u), *sessionData, r)
	if err != nil {
		ui.Log(ui.AuthLogger, "auth.webauthn.register.fail", ui.A{
			"session": session.ID,
			"user":    session.User,
			"error":   err})

		return util.ErrorResponse(w, session.ID, "passkey registration failed: "+err.Error(), http.StatusBadRequest)
	}

	// Append the new credential to the existing set and persist.
	existing := auth.WebAuthnUserFrom(u).WebAuthnCredentials()
	existing = append(existing, *credential)

	raw, err := auth.MarshalCredentials(existing)
	if err != nil {
		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	u.Passkeys = raw

	if err := auth.AuthService.WriteUser(session.ID, u); err != nil {
		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	_ = auth.AuthService.Flush()

	ui.Log(ui.AuthLogger, "auth.webauthn.register.ok", ui.A{
		"session": session.ID,
		"user":    session.User})

	w.Header().Set(defs.ContentTypeHeader, defs.JSONMediaType)
	w.WriteHeader(http.StatusOK)

	msg := `{"status":200,"msg":"passkey registered"}`
	_, _ = w.Write([]byte(msg))
	session.ResponseLength += len(msg)

	return http.StatusOK
}

// WebAuthnClearPasskeysHandler removes all stored passkeys for a user.
// DELETE /services/admin/webauthn/passkeys/{name} — Bearer token required.
// The caller must be the named user or have admin (root) permission.
func WebAuthnClearPasskeysHandler(session *Session, w http.ResponseWriter, r *http.Request) int {
	if status := passkeyGuard(w, session); status != 0 {
		return status
	}

	name := data.String(session.URLParts["name"])

	// Allow own account or admin.
	if !strings.EqualFold(name, session.User) {
		perms := auth.GetPermissions(session.ID, session.User)
		if !util.InListInsensitive(defs.RootPermission, perms...) {
			return util.ErrorResponse(w, session.ID, errors.ErrNoPermission.Error(), http.StatusForbidden)
		}
	}

	u, err := auth.AuthService.ReadUser(session.ID, name, false)
	if err != nil {
		return util.ErrorResponse(w, session.ID, "no such user: "+name, http.StatusNotFound)
	}

	u.Passkeys = nil

	if err := auth.AuthService.WriteUser(session.ID, u); err != nil {
		return util.ErrorResponse(w, session.ID, err.Error(), http.StatusInternalServerError)
	}

	_ = auth.AuthService.Flush()

	ui.Log(ui.AuthLogger, "auth.webauthn.passkeys.cleared", ui.A{
		"session": session.ID,
		"user":    name})

	// Emit a SERVER-level log entry when an admin removes another user's passkeys
	// so the action is visible in the dashboard Log tab and audit trail.
	if !strings.EqualFold(name, session.User) {
		ui.Log(ui.ServerLogger, "server.webauthn.admin.cleared.passkeys", ui.A{
			"session": session.ID,
			"admin":   session.User,
			"user":    name})
	}

	w.Header().Set(defs.ContentTypeHeader, defs.JSONMediaType)
	w.WriteHeader(http.StatusOK)

	msg := `{"status":200,"msg":"passkeys cleared"}`
	_, _ = w.Write([]byte(msg))
	session.ResponseLength += len(msg)

	return http.StatusOK
}

// updatePasskeyCounter persists the updated authenticator sign counter back into
// the user record after a successful login. This prevents replay attacks.
func updatePasskeyCounter(sessionID int, u defs.User, used *webauthn.Credential) error {
	creds := auth.WebAuthnUserFrom(u).WebAuthnCredentials()

	for i, c := range creds {
		if fmt.Sprintf("%x", c.ID) == fmt.Sprintf("%x", used.ID) {
			creds[i].Authenticator.SignCount = used.Authenticator.SignCount

			break
		}
	}

	raw, err := auth.MarshalCredentials(creds)
	if err != nil {
		return err
	}

	u.Passkeys = raw

	if err := auth.AuthService.WriteUser(sessionID, u); err != nil {
		return err
	}

	return auth.AuthService.Flush()
}

// // webauthnNotConfiguredCheck returns true (and writes a 501) when no RPID is set.
// func webauthnNotConfiguredCheck(w http.ResponseWriter, sessionID int) bool {
// 	if settings.Get(defs.WebAuthnRPIDSetting) == "" {
// 		http.Error(w, "WebAuthn not configured (ego.server.webauthn.rpid not set)", http.StatusNotImplemented)

// 		return true
// 	}

// 	return false
// }
