//
// ColumnCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Information about the columns of a table */
public struct ColumnCollection: Codable, Hashable {

    /** An array of column definitions. */
    public var columns: [Column]
    /** The number of items in the table array */
    public var count: Int

    public init(columns: [Column], count: Int) {
        self.columns = columns
        self.count = count
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case columns
        case count
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(columns, forKey: .columns)
        try container.encode(count, forKey: .count)
    }
}

