//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelError: Codable, Hashable {

    /** the HTTP status code for the response */
    public var status: Int
    /** the message text if an error occurred */
    public var msg: String

    public init(status: Int, msg: String) {
        self.status = status
        self.msg = msg
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case msg
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(msg, forKey: .msg)
    }
}

