//
// Table.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Table: Codable, Hashable {

    /** Name of the table */
    public var name: String
    /** Name fo the schema */
    public var schema: String
    /** Number of columns in the table */
    public var columns: Int
    /** Number of rows in the table */
    public var rows: Int

    public init(name: String, schema: String, columns: Int, rows: Int) {
        self.name = name
        self.schema = schema
        self.columns = columns
        self.rows = rows
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case schema
        case columns
        case rows
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(schema, forKey: .schema)
        try container.encode(columns, forKey: .columns)
        try container.encode(rows, forKey: .rows)
    }
}

