// Package rshandlers implements the HTTP endpoints for Ego's OAuth2 Resource
// Server (RS) role.  It provides three handlers:
//
//   - CallbackHandler         — /services/admin/oauth/callback
//   - AuthorizeRedirectHandler — /services/admin/oauth/authorize
//   - ConfigHandler           — /services/admin/oauth/config
//
// This package is kept separate from server/oauth so that server/oauth (which
// contains the JWT validation logic imported by the router) does not import the
// router package — avoiding a circular dependency.
package rshandlers

import (
	"encoding/json"
	"net/http"
	"strings"
	"unicode"

	"github.com/tucats/ego/internal/cli/settings"
	"github.com/tucats/ego/internal/cli/ui"
	"github.com/tucats/ego/internal/defs"
	"github.com/tucats/ego/internal/errors"
	"github.com/tucats/ego/internal/router"
	"github.com/tucats/ego/internal/server/oauth"
	"github.com/tucats/ego/internal/language/tokens"
	"github.com/tucats/ego/internal/util"
)

// callbackResponse is the JSON body returned from /services/admin/oauth/callback
// in resource-server mode, when the client needs the raw JWT access token.
type callbackResponse struct {
	// AccessToken is the JWT returned by the IdP.
	AccessToken string `json:"access_token"`

	// TokenType is always "Bearer".
	TokenType string `json:"token_type"`
}

// sanitizeLogValue replaces ASCII control characters (code points below U+0020)
// and DEL (U+007F) in s with a space, then trims leading and trailing spaces.
//
// This prevents log injection: a malicious caller can include newline characters
// in URL query parameters such as "error" and "error_description".  If those
// values were written verbatim to the structured server log (one JSON object per
// line), the embedded newlines would split one log entry into multiple lines,
// potentially inserting fake log entries or breaking JSON log parsers.
//
// Only the small set of ASCII control codes is replaced; non-ASCII Unicode
// (accented letters, CJK characters, emoji, etc.) is passed through unchanged
// because none of those affect newline-delimited JSON log format.
func sanitizeLogValue(s string) string {
	var b strings.Builder

	for _, r := range s {
		// Replace control characters (tab, newline, carriage-return, etc.)
		// and DEL.  unicode.IsControl covers the full Unicode Cc category, which
		// is a superset of ASCII control chars and includes U+007F.
		if unicode.IsControl(r) {
			b.WriteByte(' ')
		} else {
			b.WriteRune(r)
		}
	}

	return strings.TrimSpace(b.String())
}

// CallbackHandler processes GET /services/admin/oauth/callback.
//
// This endpoint is the redirect target registered with the identity provider.
// After the user authenticates with the IdP, the browser is sent here with:
//
//	code  — the short-lived authorization code to exchange for a JWT.
//	state — the opaque PKCE state token generated by AuthorizeRedirectHandler;
//	        must match the stored state to prevent CSRF attacks.
//
// If the IdP encountered an error, it passes "error" and optionally
// "error_description" instead of "code".
//
// Behavior depends on the configured mode (ego.server.oauth.mode):
//   - proxy / hybrid:         Exchange code, validate JWT, issue a native Ego
//     token and return it as {"access_token": "...", "token_type": "Bearer"}.
//   - resource-server:        Exchange code, return the raw JWT access token.
func CallbackHandler(session *router.Session, w http.ResponseWriter, r *http.Request) int {
	// If the IdP signaled an error, report it and stop.
	//
	// OAUTH-L4: both "error" and "error_description" come from URL query
	// parameters controlled by the caller (or by an attacker who crafted the
	// redirect URL).  Sanitize them before writing to the log to prevent log
	// injection via embedded newlines.  Return a fixed generic message to the
	// browser — the raw IdP error code and description are not safe to reflect
	// because they may contain attacker-controlled text.
	if idpError := r.URL.Query().Get("error"); idpError != "" {
		desc := r.URL.Query().Get("error_description")

		ui.Log(ui.AuthLogger, "oauth.rs.callback.idp.error", ui.A{
			"session": session.ID,
			"error":   sanitizeLogValue(idpError),
			"desc":    sanitizeLogValue(desc),
		})

		return util.ErrorResponse(w, session.ID,
			"OAuth2 login failed",
			http.StatusBadRequest)
	}

	// Validate the state parameter to prevent CSRF.
	state := r.URL.Query().Get("state")
	if state == "" {
		return util.ErrorResponse(w, session.ID,
			"missing state parameter in OAuth2 callback", http.StatusBadRequest)
	}

	ps, err := oauth.ValidateCallbackState(state)
	if err != nil {
		ui.Log(ui.AuthLogger, "oauth.rs.callback.bad.state", ui.A{
			"session": session.ID,
			"error":   err.Error(),
		})

		return util.ErrorResponse(w, session.ID, errors.Localize(err, session.Language), http.StatusBadRequest)
	}

	// Extract the authorization code.
	code := r.URL.Query().Get("code")
	if code == "" {
		return util.ErrorResponse(w, session.ID,
			"missing code parameter in OAuth2 callback", http.StatusBadRequest)
	}

	// Exchange the code for tokens.
	cfg := oauth.GetConfig()

	accessToken, _, err := oauth.ExchangeCodePublic(cfg, code, ps.CodeVerifier)
	if err != nil {
		// OAUTH-L4: log the full error detail server-side but return a fixed
		// generic message to the browser.  The error string from ExchangeCode
		// can contain the IdP token endpoint URL and the IdP's own error body,
		// which aids an attacker who is probing the token exchange behavior.
		ui.Log(ui.AuthLogger, "oauth.rs.callback.exchange.failed", ui.A{
			"session": session.ID,
			"error":   err.Error(),
		})

		return util.ErrorResponse(w, session.ID,
			"OAuth2 login failed", http.StatusBadGateway)
	}

	// Validate the received JWT to extract the user identity and permissions.
	user, permissions, err := oauth.ValidateJWT(session.ID, accessToken)
	if err != nil {
		// OAUTH-L4: ValidateJWT already logs the rejection via oauth.rs.jwt.invalid
		// (inside the ValidateJWT function itself).  Here we only need to return a
		// generic message to the browser — the specific validation failure reason
		// (signature mismatch, expiry, issuer, audience, missing claim) would help
		// an attacker probe token validation behavior.
		return util.ErrorResponse(w, session.ID,
			"OAuth2 login failed", http.StatusBadGateway)
	}

	ui.Log(ui.AuthLogger, "oauth.rs.callback.ok", ui.A{
		"session": session.ID,
		"user":    user,
		"mode":    cfg.Mode,
	})

	// In proxy and hybrid modes issue a native Ego token; in resource-server
	// mode return the raw JWT.
	if cfg.Mode == oauth.ModeProxy || cfg.Mode == oauth.ModeHybrid {
		egoToken, err := tokens.New(
			user,
			permissionsToData(permissions),
			settings.Get(defs.ServerTokenExpirationSetting),
			defs.InstanceID,
			session.ID,
		)
		if err != nil {
			// L3: log the full error server-side but return a generic message to
			// the browser.
			//
			// Why this matters:
			//
			//   tokens.New can fail for several internal reasons: the signing key
			//   may be unavailable, the configured token expiry string may be
			//   malformed, or the instance ID may not be set.  All of these are
			//   operator configuration problems, not user errors.  Appending
			//   err.Error() to the HTTP response body (the pre-fix behavior) leaks
			//   these internal details — file paths, config key names, key formats
			//   — to any browser that can trigger this path.
			//
			//   The server-side log entry (oauth.rs.callback.token.failed) provides
			//   the full detail to the operator who needs to diagnose the problem,
			//   while the browser sees only "OAuth2 login failed", consistent with
			//   every other error in this handler.
			ui.Log(ui.ServerLogger, "oauth.rs.callback.token.failed", ui.A{
				"session": session.ID,
				"user":    user,
				"error":   err.Error(),
			})

			return util.ErrorResponse(w, session.ID,
				"OAuth2 login failed",
				http.StatusInternalServerError)
		}

		payload := map[string]string{
			"access_token": egoToken,
			"token_type":   "Bearer",
			"user":         user,
		}

		w.Header().Set("Content-Type", defs.JSONMediaType)
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(payload)

		return http.StatusOK
	}

	// resource-server mode: return the JWT.
	resp := callbackResponse{
		AccessToken: accessToken,
		TokenType:   "Bearer",
	}

	w.Header().Set("Content-Type", defs.JSONMediaType)
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(resp)

	return http.StatusOK
}

// permissionsToData formats a permission slice as a comma-separated string for
// storage in a token's Data field.
//
// L5 — strings.Join instead of manual accumulation:
//
//	The previous implementation used `result += ","` + `result += p` inside a
//	loop.  In Go, strings are immutable: every += allocates a new backing array
//	and copies all previous bytes into it.  For n permissions the total bytes
//	copied is O(1 + 2 + … + n) = O(n²).  With a typical set of five or fewer
//	permissions the difference is negligible, but it is unnecessary complexity.
//
//	strings.Join allocates exactly one output string after a single pass to
//	compute the total length — O(n) time and O(n) space — and is the idiomatic
//	Go solution.
func permissionsToData(permissions []string) string {
	return strings.Join(permissions, ",")
}
