package oauth

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// AuthorizeURL builds the URL that a browser should be redirected to in order
// to start the Authorization Code + PKCE flow.
//
// The function:
//  1. Fetches the OIDC discovery document to locate the authorization_endpoint.
//  2. Generates a random PKCE state string and code_verifier pair.
//  3. Derives the code_challenge (S256 hash of the verifier).
//  4. Constructs the full authorization URL with all required OAuth2 parameters.
//
// The caller is responsible for redirecting the browser to the returned URL and
// for storing the state and code_verifier to validate the callback.
//
// Parameters:
//   - cfg: the resolved RS configuration (provider URL, client ID, scopes, etc.)
//
// Returns the redirect URL, the state token, the code_verifier, and any error.
func AuthorizeURL(cfg rsConfig) (redirectURL, state, codeVerifier string, err error) {
	doc, err := discoverEndpoints(cfg.Provider)
	if err != nil {
		return "", "", "", fmt.Errorf("OIDC discovery: %w", err)
	}

	if doc.AuthorizationEndpoint == "" {
		return "", "", "", fmt.Errorf("OIDC discovery document has no authorization_endpoint")
	}

	// Generate a random PKCE state and code_verifier.
	state, codeVerifier, err = newState(cfg.RedirectURI)
	if err != nil {
		return "", "", "", err
	}

	// Derive the S256 code_challenge from the verifier.
	challenge := codeChallenge(codeVerifier)

	// Build the query parameters for the authorization request.
	params := url.Values{}
	params.Set("response_type", "code")
	params.Set("client_id", cfg.ClientID)
	params.Set("redirect_uri", cfg.RedirectURI)
	params.Set("scope", cfg.Scopes)
	params.Set("state", state)
	params.Set("code_challenge", challenge)
	params.Set("code_challenge_method", "S256")

	// Append the parameters to the authorization endpoint URL.
	authURL := doc.AuthorizationEndpoint

	if strings.Contains(authURL, "?") {
		authURL += "&" + params.Encode()
	} else {
		authURL += "?" + params.Encode()
	}

	return authURL, state, codeVerifier, nil
}

// tokenExchangeResponse is the JSON body returned by the IdP's token endpoint
// after a successful Authorization Code exchange.  Field names follow RFC 6749 §5.1.
type tokenExchangeResponse struct {
	// AccessToken is the JWT access token.
	AccessToken string `json:"access_token"`

	// TokenType is always "Bearer".
	TokenType string `json:"token_type"`

	// ExpiresIn is the token lifetime in seconds.
	ExpiresIn int64 `json:"expires_in"`

	// RefreshToken may be included when the "offline_access" scope was granted.
	RefreshToken string `json:"refresh_token,omitempty"`

	// IDToken is included when the "openid" scope was granted.
	IDToken string `json:"id_token,omitempty"`

	// Scope is the space-delimited list of scopes actually granted.
	Scope string `json:"scope,omitempty"`

	// Error is populated by the IdP on failure.
	Error string `json:"error,omitempty"`

	// ErrorDescription gives more detail about the failure.
	ErrorDescription string `json:"error_description,omitempty"`
}

// ExchangeCode exchanges an authorization code (received at the callback endpoint
// after the user authenticated with the IdP) for a JWT access token.
//
// The exchange is a server-side HTTP POST to the IdP's token endpoint.  It
// includes the authorization code, the Ego client credentials, the redirect URI
// (which must exactly match the one in the original authorization request), and the
// PKCE code_verifier that corresponds to the code_challenge sent in the first step.
//
// Parameters:
//   - cfg:          the resolved RS configuration.
//   - code:         the authorization code from the IdP callback query parameter.
//   - codeVerifier: the PKCE verifier generated by AuthorizeURL for this flow.
//
// Returns the access token JWT string and any ID token JWT string, or an error if
// the exchange fails (invalid code, PKCE mismatch, network error, etc.).
func ExchangeCode(cfg rsConfig, code, codeVerifier string) (accessToken, idToken string, err error) {
	doc, err := discoverEndpoints(cfg.Provider)
	if err != nil {
		return "", "", fmt.Errorf("OIDC discovery: %w", err)
	}

	if doc.TokenEndpoint == "" {
		return "", "", fmt.Errorf("OIDC discovery document has no token_endpoint")
	}

	// Build the POST body as application/x-www-form-urlencoded.
	form := url.Values{}
	form.Set("grant_type", "authorization_code")
	form.Set("code", code)
	form.Set("redirect_uri", cfg.RedirectURI)
	form.Set("client_id", cfg.ClientID)
	form.Set("code_verifier", codeVerifier)

	// Confidential clients include their secret; public clients omit it.
	if cfg.ClientSecret != "" {
		form.Set("client_secret", cfg.ClientSecret)
	}

	req, err := http.NewRequest(http.MethodPost, doc.TokenEndpoint, strings.NewReader(form.Encode()))
	if err != nil {
		return "", "", fmt.Errorf("building token exchange request: %w", err)
	}

	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", "", fmt.Errorf("token exchange POST to %s: %w", doc.TokenEndpoint, err)
	}

	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", "", fmt.Errorf("reading token exchange response: %w", err)
	}

	var result tokenExchangeResponse
	if err := json.Unmarshal(body, &result); err != nil {
		return "", "", fmt.Errorf("parsing token exchange response: %w", err)
	}

	// The IdP signals errors with HTTP 4xx/5xx AND an "error" field in the body.
	if result.Error != "" {
		return "", "", fmt.Errorf("token exchange error %q: %s", result.Error, result.ErrorDescription)
	}

	if resp.StatusCode != http.StatusOK {
		return "", "", fmt.Errorf("token exchange returned HTTP %d", resp.StatusCode)
	}

	if result.AccessToken == "" {
		return "", "", fmt.Errorf("token exchange response contains no access_token")
	}

	return result.AccessToken, result.IDToken, nil
}
