package oauth

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"sync"
	"time"

	"github.com/tucats/ego/errors"
)

// pendingState holds the PKCE parameters associated with an in-flight
// Authorization Code flow request.  It is stored in memory keyed by the
// opaque "state" string that the browser round-trips to the callback.
type pendingState struct {
	// CodeVerifier is the high-entropy random string generated by Ego before
	// redirecting the browser to the IdP.  The IdP receives the SHA-256 hash
	// (the "code_challenge"); Ego sends the raw verifier when exchanging the
	// code for tokens.  This prevents an attacker who intercepts the
	// authorization code from using it without the verifier.
	CodeVerifier string

	// CreatedAt records when this state was generated.  Entries older than
	// stateMaxAge are rejected by validateState to prevent replay attacks.
	CreatedAt time.Time
}

// stateMaxAge is the maximum lifetime of a pending PKCE state entry.
// Authorization Code flow must complete within this window after the
// browser is redirected to the IdP.
const stateMaxAge = 10 * time.Minute

// statePurgeInterval controls how often the background goroutine runs
// purgeExpiredStates.  It is shorter than stateMaxAge so that expired entries
// are cleaned up promptly and cannot accumulate between purge cycles (OAUTH-M5).
//
// A 2-minute interval means at most ~2 minutes of dead entries linger between
// sweeps.  Given the maxPendingStates cap below, 2 minutes is the worst-case
// window during which a flood of requests could fill the map before the purge
// runs and frees space.
const statePurgeInterval = 2 * time.Minute

// maxPendingStates is the maximum number of in-flight PKCE state entries
// allowed at any one time (OAUTH-M5).
//
// Each call to GET /services/admin/oauth/authorize creates one entry.  Without
// a cap, a sustained flood of requests could grow stateStore.items without
// bound, consuming memory until the server OOMs.
//
// 500 concurrent pending OAuth2 flows is far more than any realistic production
// load (each entry represents a user who is currently looking at the IdP login
// page and has not yet completed or abandoned the flow).  Raising this limit
// does not directly improve security; lowering it reduces the memory budget an
// attacker can consume but risks rejecting legitimate concurrent users.
const maxPendingStates = 500

// stateStore holds all pending PKCE state entries, keyed by the opaque
// state string.  Access is protected by a mutex.
var stateStore struct {
	mu    sync.Mutex
	items map[string]*pendingState
}

// init pre-allocates the state store map.
func init() {
	stateStore.items = make(map[string]*pendingState)
}

// newState generates a cryptographically random opaque state string and a PKCE
// code_verifier, stores them together in the state store, and returns both.
//
// The state string and code_verifier are each 32 bytes of random data encoded
// as base64url (without padding) — 43-character strings.  This is well above
// the 128-bit minimum entropy recommended by RFC 7636 §7.1.
//
// Returns (state, codeVerifier, error).
func newState() (string, string, error) {
	stateBytes := make([]byte, 32)
	if _, err := rand.Read(stateBytes); err != nil {
		return "", "", errors.New(errors.ErrPKCEStateGenerate).Context(err.Error())
	}

	verifierBytes := make([]byte, 32)
	if _, err := rand.Read(verifierBytes); err != nil {
		return "", "", errors.New(errors.ErrPKCEVerifierGenerate).Context(err.Error())
	}

	state := base64.RawURLEncoding.EncodeToString(stateBytes)
	verifier := base64.RawURLEncoding.EncodeToString(verifierBytes)

	// OAUTH-M5: enforce the global cap before inserting.  We acquire the mutex
	// for the count check AND the insert in one critical section so there is no
	// window between the check and the write where another goroutine could sneak
	// in and push the count over the limit (a classic TOCTOU race).
	stateStore.mu.Lock()
	defer stateStore.mu.Unlock()

	// If the store is at its cap, try reclaiming expired entries before giving up.
	//
	// L4 — on-demand purge when the store is full:
	//
	//   The background goroutine (started in Initialize) sweeps the store every
	//   statePurgeInterval (2 minutes).  Between sweeps, a user who starts an
	//   OAuth2 flow and then closes the browser window without completing it
	//   leaves a "zombie" entry that occupies a slot until the sweep fires.
	//
	//   Under a benign traffic pattern this is harmless.  Under an attack, an
	//   adversary can flood the server with 500 GET /authorize requests, filling
	//   the store, and then wait for stateMaxAge (10 minutes) to let them expire
	//   naturally.  During the gap between expiry and the next 2-minute sweep,
	//   all legitimate new flows are rejected with 503 — a denial-of-service
	//   window of up to 2 minutes per attack cycle.
	//
	//   The fix: when the store is full, perform an immediate inline sweep before
	//   deciding whether to return an error.  Because we already hold stateStore.mu
	//   (acquired above), the sweep is safe without an additional lock.  After the
	//   sweep we re-check the length; if at least one slot was freed, the new entry
	//   can be inserted without waiting for the background goroutine.
	//
	//   This does not affect the attack-prevention property: a determined attacker
	//   who keeps the store continuously full with fresh (not-yet-expired) entries
	//   still triggers a 503, as before.  The fix only helps when expired-but-
	//   unswept entries were blocking legitimate requests.
	if len(stateStore.items) >= maxPendingStates {
		// Inline sweep: remove any entry whose age exceeds stateMaxAge.
		// This mirrors purgeExpiredStates() but runs under the lock we already hold.
		for key, ps := range stateStore.items {
			if time.Since(ps.CreatedAt) > stateMaxAge {
				delete(stateStore.items, key)
			}
		}

		// Re-check after the sweep.  If expired entries were reclaimed, the count
		// is now below maxPendingStates and the insert can proceed normally.
		// If the store is still full (all entries are genuinely in-flight), return
		// the original error — the cap is serving its intended purpose.
		if len(stateStore.items) >= maxPendingStates {
			return "", "", errors.New(errors.ErrOAuthTooManyFlows).Context(
				fmt.Sprintf("%d active", maxPendingStates))
		}
	}

	stateStore.items[state] = &pendingState{
		CodeVerifier: verifier,
		CreatedAt:    time.Now(),
	}

	return state, verifier, nil
}

// validateState looks up the given state string, removes it from the store
// (states are single-use), and returns the associated pendingState.
//
// Returns an error when:
//   - The state is not found (never issued, or already consumed).
//   - The state is older than stateMaxAge (possible replay attack or
//     user took too long to complete the IdP login).
func validateState(state string) (*pendingState, error) {
	stateStore.mu.Lock()
	defer stateStore.mu.Unlock()

	ps, ok := stateStore.items[state]
	if !ok {
		return nil, errors.New(errors.ErrOAuthStateInvalid)
	}

	// Always delete the entry — states are strictly single-use.
	delete(stateStore.items, state)

	if time.Since(ps.CreatedAt) > stateMaxAge {
		return nil, errors.New(errors.ErrOAuthStateExpired).Context(fmt.Sprintf("max age %v", stateMaxAge))
	}

	return ps, nil
}

// codeChallenge derives the PKCE code_challenge from a code_verifier using the
// S256 method: BASE64URL(SHA256(ASCII(code_verifier))).
//
// This is the only PKCE method Ego supports (the "plain" method is insecure
// because it offers no benefit over transmitting the verifier directly).
func codeChallenge(verifier string) string {
	h := sha256.Sum256([]byte(verifier))

	return base64.RawURLEncoding.EncodeToString(h[:])
}

// purgeExpiredStates removes any pending state entries older than stateMaxAge.
// It is called periodically by a background goroutine started in Initialize(),
// and is also called directly by tests to trigger cleanup without waiting for
// the natural expiry.
func purgeExpiredStates() {
	stateStore.mu.Lock()
	defer stateStore.mu.Unlock()

	for key, ps := range stateStore.items {
		if time.Since(ps.CreatedAt) > stateMaxAge {
			delete(stateStore.items, key)
		}
	}
}
