package oauth

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"sync"
	"time"
)

// pendingState holds the PKCE parameters associated with an in-flight
// Authorization Code flow request.  It is stored in memory keyed by the
// opaque "state" string that the browser round-trips to the callback.
type pendingState struct {
	// CodeVerifier is the high-entropy random string generated by Ego before
	// redirecting the browser to the IdP.  The IdP receives the SHA-256 hash
	// (the "code_challenge"); Ego sends the raw verifier when exchanging the
	// code for tokens.  This prevents an attacker who intercepts the
	// authorization code from using it without the verifier.
	CodeVerifier string

	// RedirectURI is the callback URL included in the authorization request.
	// It must be re-sent, unchanged, in the token exchange.
	RedirectURI string

	// CreatedAt records when this state was generated.  Entries older than
	// stateMaxAge are rejected by validateState to prevent replay attacks.
	CreatedAt time.Time
}

// stateMaxAge is the maximum lifetime of a pending PKCE state entry.
// Authorization Code flow must complete within this window after the
// browser is redirected to the IdP.
const stateMaxAge = 10 * time.Minute

// statePurgeInterval controls how often the background goroutine runs
// purgeExpiredStates.  It is shorter than stateMaxAge so that expired entries
// are cleaned up promptly and cannot accumulate between purge cycles (OAUTH-M5).
//
// A 2-minute interval means at most ~2 minutes of dead entries linger between
// sweeps.  Given the maxPendingStates cap below, 2 minutes is the worst-case
// window during which a flood of requests could fill the map before the purge
// runs and frees space.
const statePurgeInterval = 2 * time.Minute

// maxPendingStates is the maximum number of in-flight PKCE state entries
// allowed at any one time (OAUTH-M5).
//
// Each call to GET /services/admin/oauth/authorize creates one entry.  Without
// a cap, a sustained flood of requests could grow stateStore.items without
// bound, consuming memory until the server OOMs.
//
// 500 concurrent pending OAuth2 flows is far more than any realistic production
// load (each entry represents a user who is currently looking at the IdP login
// page and has not yet completed or abandoned the flow).  Raising this limit
// does not directly improve security; lowering it reduces the memory budget an
// attacker can consume but risks rejecting legitimate concurrent users.
const maxPendingStates = 500

// stateStore holds all pending PKCE state entries, keyed by the opaque
// state string.  Access is protected by a mutex.
var stateStore struct {
	mu    sync.Mutex
	items map[string]*pendingState
}

// init pre-allocates the state store map.
func init() {
	stateStore.items = make(map[string]*pendingState)
}

// newState generates a cryptographically random opaque state string and a PKCE
// code_verifier, stores them together in the state store, and returns both.
//
// The state string and code_verifier are each 32 bytes of random data encoded
// as base64url (without padding) — 43-character strings.  This is well above
// the 128-bit minimum entropy recommended by RFC 7636 §7.1.
//
// The redirectURI is stored alongside the state so that the callback handler
// can verify that the URI was not tampered with between the authorization
// request and the token exchange.
//
// Returns (state, codeVerifier, error).
func newState(redirectURI string) (string, string, error) {
	stateBytes := make([]byte, 32)
	if _, err := rand.Read(stateBytes); err != nil {
		return "", "", fmt.Errorf("generating PKCE state: %w", err)
	}

	verifierBytes := make([]byte, 32)
	if _, err := rand.Read(verifierBytes); err != nil {
		return "", "", fmt.Errorf("generating PKCE code_verifier: %w", err)
	}

	state := base64.RawURLEncoding.EncodeToString(stateBytes)
	verifier := base64.RawURLEncoding.EncodeToString(verifierBytes)

	// OAUTH-M5: enforce the global cap before inserting.  We acquire the mutex
	// for the count check AND the insert in one critical section so there is no
	// window between the check and the write where another goroutine could sneak
	// in and push the count over the limit (a classic TOCTOU race).
	stateStore.mu.Lock()
	defer stateStore.mu.Unlock()

	// If the store is already at its cap, refuse to add more entries.  This
	// prevents an unauthenticated flood of GET /authorize requests from
	// consuming unbounded memory.
	//
	// Returning an error here causes AuthorizeRedirectHandler to respond 503
	// (Service Unavailable) to the browser — far better than silently
	// accepting the entry and letting the server run out of memory.
	if len(stateStore.items) >= maxPendingStates {
		return "", "", fmt.Errorf(
			"too many pending OAuth2 flows (%d active); try again shortly",
			maxPendingStates,
		)
	}

	stateStore.items[state] = &pendingState{
		CodeVerifier: verifier,
		RedirectURI:  redirectURI,
		CreatedAt:    time.Now(),
	}

	return state, verifier, nil
}

// validateState looks up the given state string, removes it from the store
// (states are single-use), and returns the associated pendingState.
//
// Returns an error when:
//   - The state is not found (never issued, or already consumed).
//   - The state is older than stateMaxAge (possible replay attack or
//     user took too long to complete the IdP login).
func validateState(state string) (*pendingState, error) {
	stateStore.mu.Lock()
	defer stateStore.mu.Unlock()

	ps, ok := stateStore.items[state]
	if !ok {
		return nil, fmt.Errorf("unknown or already-used OAuth2 state parameter")
	}

	// Always delete the entry — states are strictly single-use.
	delete(stateStore.items, state)

	if time.Since(ps.CreatedAt) > stateMaxAge {
		return nil, fmt.Errorf("OAuth2 state parameter has expired (max age %v)", stateMaxAge)
	}

	return ps, nil
}

// codeChallenge derives the PKCE code_challenge from a code_verifier using the
// S256 method: BASE64URL(SHA256(ASCII(code_verifier))).
//
// This is the only PKCE method Ego supports (the "plain" method is insecure
// because it offers no benefit over transmitting the verifier directly).
func codeChallenge(verifier string) string {
	h := sha256.Sum256([]byte(verifier))

	return base64.RawURLEncoding.EncodeToString(h[:])
}

// purgeExpiredStates removes any pending state entries older than stateMaxAge.
// It is called periodically by a background goroutine started in Initialize(),
// and is also called directly by tests to trigger cleanup without waiting for
// the natural expiry.
func purgeExpiredStates() {
	stateStore.mu.Lock()
	defer stateStore.mu.Unlock()

	for key, ps := range stateStore.items {
		if time.Since(ps.CreatedAt) > stateMaxAge {
			delete(stateStore.items, key)
		}
	}
}
