package bytecode

import (
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/tucats/ego/internal/cli/settings"
	"github.com/tucats/ego/internal/cli/ui"
	"github.com/tucats/ego/internal/defs"
	"github.com/tucats/ego/internal/errors"
	"github.com/tucats/ego/internal/language/data"
	"github.com/tucats/ego/internal/language/symbols"
	"github.com/tucats/ego/internal/language/tokenizer"
)

// For a function call with a receiver, this is the structure that
// describes the receiver's name and current value.
type this struct {
	// The name of the receiver variable
	name string

	// The current value of the receiver variable when a function call
	// is made. We save it here because the symbol scope stack changes
	// during a function call so the current value may not be accessible
	// when needed in the scope of the called function.
	value any
}

// For a given try/catch block, this is the runtime info needed for the exception
// handler to know if a catch clause is to be invoked.
type tryInfo struct {
	// Branch destination in a try/catch block where execution transfers
	// to handle the catch clause.
	addr int

	// List of errors that the catch block is able to handle.
	catches []error
}

// This value is updated atomically during context creation.
var nextThreadID int32 = 0

// MaxStackSize records the largest stack size encountered during a
// stack push operation. This can be used to determine if the initial
// stack size is adequate.
var MaxStackSize int32

// InstructionsExecuted counts the number of byte code instructions
// executed.
var InstructionsExecuted int64

// deferStatement is a structure that holds the information about a
// defer statement previously processed.
type deferStatement struct {
	// Source location
	name string

	// Function target
	target any

	// Receiver stack in effect for this defer statement
	receiverStack []this

	// Symbols active for this defer statement
	symbols *symbols.SymbolTable

	// Arguments
	args []any
}

// Context holds the runtime information about an instance of bytecode being
// executed.
type Context struct {
	// Name of the function currently being executed
	name string

	// Package name of the function currently being executed. If not running
	// within a package, this is an empty string.
	pkg string

	// Module name for the current function. This is typically the base part
	// of the source file containing the function being execute. When running
	// interactively in REPL mode, this is always an empty string.
	module string

	// The bytecode array currently being executed.
	bc *ByteCode

	// The active symbol table for the current function.
	symbols *symbols.SymbolTable

	// The root symbol table for this Context's run, cached once at
	// NewContext time. A table's ancestry is never changed once a program
	// starts executing (see PERFORMANCE.md Finding 14, Phase 2), so every
	// symbol table reachable during this run shares this same root — reading
	// it here avoids an O(depth) symbols.(*SymbolTable).Root() walk on every
	// call site that needs the root table (e.g. callFramePop, restoring the
	// global "extensions" setting on every function return).
	rootSymbols *symbols.SymbolTable

	// The pointer to the tokenizer for the source code being executed. This
	// is only used for error handling or when the debugger is active.
	tokenizer *tokenizer.Tokenizer

	// The runtime stack. The stack is a LIFO stack that supports the RPN
	// execution mode of expressions as generated by the Ego compiler.
	stack []any

	// This is a list of the nested try/catch blocks. When entering a new
	// try/catch block, a new tryInfo is pushed onto this stack. When an
	// exception occurs, the stack is searched to see if a catch block
	// is defined for the current exception. When exiting the try/catch block,
	// the tryInfo is popped from the stack.
	tryStack []tryInfo

	// The range stack is used for managing nested for loops. Each loop type
	// creates a range definition object, and is pushed on the stack. When the
	// end of loop is hit, the range definition object is re-evaluated and if
	// the loop conditions is satisfied, the loop is exited and the range definition
	// object is popped from the stack.
	rangeStack []*rangeDefinition

	// The timer stack is used to manage timed operations.
	timerStack []time.Time

	// The current value of the "this" variable. This is used when a function call
	// is made to a method that has a receiver. The current function may be executed
	// as a result of nested receiver invocations (such as a.b.c.d(), for example).
	// This stack manages the current this value, and at the end of the function call,
	// the current this value is popped from the stack.
	receiverStack []this

	// This manages the list of defer statements. Each defer statement generates code
	// and context information for it's execution. Defer operations are executed in the
	// order they were added, and the execution of the defer statements is performed
	// when the function call returns.
	deferStack []deferStatement

	// output is the io.Writer used by print/newline bytecodes to emit program output.
	// It is always non-nil: NewContext initializes it to os.Stdout, and
	// EnableConsoleOutput(false) redirects it to captureBuffer.
	output io.Writer

	// captureBuffer, when non-nil, holds program output captured instead of being
	// sent to stdout. It is set by EnableConsoleOutput(false) and read by
	// GetOutput, ClearOutput, and sayByteCode.
	captureBuffer *strings.Builder

	// outputStack backs the "@capture" directive (see compiler package's
	// captureDirective and this package's capture.go). Every time a
	// "@capture" block starts, the CURRENT value of the "output" field above
	// is pushed onto this slice -- like setting a bookmark -- and a brand
	// new buffer is installed in its place. When the "@capture" block ends,
	// the bookmark is popped back off and "output" is restored to exactly
	// what it was before, whatever that happened to be.
	//
	// This is a completely separate mechanism from captureBuffer/
	// EnableConsoleOutput above. Those implement a single on/off switch used
	// by the "@test"/"@pass" directives to gather up everything a single
	// test prints and show it as one tidy line; that switch has no memory of
	// "what it was before" (turning it back on always means "go back to the
	// real terminal", full stop). If "@capture" reused that same switch, an
	// "@capture" block used INSIDE an "@test" (the whole point of this
	// feature) would clobber the test's own in-progress buffer and leave the
	// rest of the test's output going to the real terminal instead of being
	// gathered up neatly. Keeping a dedicated, stacked bookmark here lets
	// "@capture" nest correctly inside itself AND inside "@test", because
	// restoring always means "go back to whatever the previous layer was" --
	// the real terminal, an enclosing "@test", or an enclosing "@capture" --
	// never a hard-coded value.
	outputStack []io.Writer

	// The function result is stored here if there is a return statement with a
	// result value. If there are multiple return values, this is an array slice
	// of values.
	result any

	// resultSet is true when a return statement explicitly set result, even
	// when result is nil. This distinguishes "return nil" from "no return".
	resultSet bool

	// Mutex to protect context updates during concurrent execution. For example,
	// if the context is for a function that invokes go routine(s), those routines
	// may need to update this context... the mutex is used to ensure that only one
	// goroutine can update the context at a time.
	mux sync.RWMutex

	// If there is a go routine associated with this context, this is the error state
	// if any.
	goErr error

	// This contains the text of the executing code. This is used by the debugger, and
	// is normally an empty string during non-debug mode.
	source string

	// The current bytecode instruction being executed, zero-based.
	programCounter int

	// The current stack pointer value in the stack slide.
	stackPointer int

	// The pointer within the current stack where the current function call's frame information
	// is stored. A frame is the information needed to update the context when the function
	// returns (restoring the caller's stack pointer, program counter, etc.) A
	framePointer int

	// The line number of the current source code being executed. This is updated by the
	// _Line bytecode and is used by the debugger and to formulate error messages.
	line int

	// The line number of the last line of source that was output during execution
	// tracing.
	lastLine int

	// The nested scope depth of the current symbol table. A depth of zero means no
	// symbol tables have been pushed on the symbol table stack.
	blockDepth int

	// This is an offset in the argument count used to get arguments from the stack
	// during a call. Normally this value is zero, but if the runtime requires adding
	// additional information to the call (such as an the invocation of a goroutine)
	// this value may be a positive non-zero value.
	argCountDelta int

	// If non-zero, it means the defer item we are executing at the moment has receiver
	// items associated with the defer invocation.
	deferThisSize int

	// The pointer to the symbol table stack active at the time when the current defer
	// block was created. The runtime context of a defer must be able to access the local
	// symbol value sat the time of the defer.
	deferSymbols *symbols.SymbolTable

	// An internal numeric unique value indicating the current thread number. This is not
	// related to operating system or Go thread id values. It is used to uniquely identify
	// each Ego thread running a go routine.
	threadID int32

	// If true, then symbol access for this context is allowed to see all nested symbol tables
	// above it, even if they are normally considered private. This is used to support debugger
	// and specific runtime functions that are allowed to display symbol table data.
	fullSymbolScope bool

	// If true, the current bytecode is running, and at the completion of each bytecode will
	// fetch the next instruction. When the bytecode stream is done executing, this is set
	// to false. Uses atomic.Bool so that the SIGINT goroutine spawned in RunFromAddress can
	// safely write it while the main execution loop reads it on every iteration.
	running atomic.Bool

	// Flag indicating that the program was interrupted by a signal. If under control of the
	// debugger, causes the program to return to the debugger REPL. Uses atomic.Bool for the
	// same reason as running — written by the SIGINT goroutine, read by the execution loop.
	interrupted atomic.Bool

	// Indicator of the type strictness for this context. Each new context inherits the
	// type strictness of the parent context. However, the code cah change the strictness
	// within a given context (some of the runtime packages do this when they need to be
	// type independent, for example).
	typeStrictness int

	// panicActive is true while panic() is unwinding the call stack looking for a
	// deferred recover() call. Set by UserPanic opcode, cleared by Recover opcode.
	panicActive bool

	// panicValue holds the value passed to panic(). Only meaningful when panicActive is true.
	panicValue any

	// panicContext is non-nil when this context is a deferred-function child context that
	// was spawned during panic unwinding. It points back to the panicking parent context so
	// that a recover() call inside the deferred function can locate and clear the panic state.
	panicContext *Context

	// If true, the context is being used for debugging. When set, each _Line bytecode
	// causes control to return to the debugger REPL to allow the debugger to determine
	// if there is a breakpoint or step operation that is active that would result in a
	// prompt to the user. If no step or breakpoint is active, the debugger resumes the
	// execution of the bytecode at the next bytecode after the _Line.
	debugging bool

	// When true, this bytecode is in single-step mode and control returns to the debugger
	// after each _Line bytecode.
	singleStep bool

	// If true, control returns to the debugger after each _Return bytecode.
	breakOnReturn bool

	// IF true, control does NOT return to the debugger when calling into another
	// bytecode function.
	stepOver bool

	// When true, try/catch will not catch any errors not enumerated in the catch
	// statement. If false, then all errors go to the catch block.
	throwUncheckedErrors bool

	// When an error occurs, does the full stack get printed int he trace, or only the
	// first few items. This is normally off, but for complicated debugging situations it
	// may be helpful to see the entire stack at each statement or bytecode instruction.
	fullStackTrace bool

	// When true, each bytecode is traced, including the bytecode name and source line.
	tracing bool

	// When true, language extensions are enabled.
	extensions bool

	// When true, the context runs in a sandbox for controlling I/O
	sandboxedIO atomic.Bool

	// When true, the context runs without allows Exec functions (subprocesses)
	sandboxedExec atomic.Bool

	// When true, this context is shared by multiple goroutines. This causes some operations
	// to perform additional serialization.
	shared atomic.Bool
}

// NewContext generates a new context. It must be passed a symbol table and a bytecode
// array. A context holds the runtime state of a given execution unit (program counter,
// runtime stack, symbol table) and is used to actually run bytecode. The bytecode
// can continue to be modified after it is associated with a context.
func NewContext(s *symbols.SymbolTable, b *ByteCode) *Context {
	var err error

	// Make sure globals are initialized.
	initializeDispatch()

	// Determine the name using the associated ByteCode object.
	name := ""
	if b != nil {
		name = b.name
	}

	// Determine whether static data typing is in effect. This is
	// normally off, but can be set by a global variable (which is
	// ultimately set by a profile setting or CLI option).
	static := defs.NoTypeEnforcement

	if s, found := s.Get(defs.TypeCheckingVariable); found {
		if static, err = data.Int(s); err != nil && ui.IsActive(ui.InternalLogger) {
			ui.Log(ui.InternalLogger, "runtime.typing.error", ui.A{
				"name":  defs.TypeCheckingVariable,
				"error": err})
		}

		if static < defs.StrictTypeEnforcement || static > defs.NoTypeEnforcement {
			static = defs.NoTypeEnforcement
		}
	}

	// If we weren't given a table, create an empty temp table.
	if s == nil {
		s = symbols.NewSymbolTable("")
	}

	// Resolve the root table once here rather than re-deriving it on every
	// later call site that needs it (see PERFORMANCE.md Finding 14, Phase 2).
	rootTable := s.Root()

	extensions := false

	if v, ok := rootTable.Get(defs.ExtensionsVariable); ok {
		if extensions, err = data.Bool(v); err != nil && ui.IsActive(ui.InternalLogger) {
			ui.Log(ui.InternalLogger, "runtime.extensions.error", ui.A{
				"name":  defs.ExtensionsVariable,
				"error": err})
		}
	}

	// Create the context object.
	ctx := Context{
		name:                 name,
		threadID:             atomic.AddInt32(&nextThreadID, 1),
		bc:                   b,
		programCounter:       0,
		stack:                make([]any, initialStackSize),
		stackPointer:         0,
		framePointer:         0,
		typeStrictness:       static,
		line:                 0,
		output:               os.Stdout,
		symbols:              s,
		rootSymbols:          rootTable,
		fullSymbolScope:      true,
		receiverStack:        nil,
		deferStack:           make([]deferStatement, 0),
		throwUncheckedErrors: settings.GetBool(defs.ThrowUncheckedErrorsSetting),
		fullStackTrace:       settings.GetBool(defs.FullStackTraceSetting),
		tryStack:             make([]tryInfo, 0),
		rangeStack:           make([]*rangeDefinition, 0),
		timerStack:           make([]time.Time, 0),
		extensions:           extensions,
	}
	contextPointer := &ctx
	contextPointer.SetByteCode(b)

	// Initialize the default sandbox settings based on the global process state.
	ctx.sandboxedExec.Store(!settings.GetBool(defs.ExecPermittedSetting))
	ctx.sandboxedIO.Store("" != settings.Get(defs.SandboxPathSetting))

	s.SetAlways(defs.SandboxedExecSymbolName, ctx.sandboxedExec.Load())
	s.SetAlways(defs.SandboxedIOSymbolName, ctx.sandboxedIO.Load())

	return contextPointer
}

// Set the context to sandboxed mode if the flag is true. This limits
// where the i/o system can reference files and prevents operations that
// spawn a subprocess. This is set in the context for quick access from
// bytecodes, and also in the symbol table so that it can be accessed by
// runtime functions as needed.
func (c *Context) Sandboxed(flag bool) *Context {
	if c != nil {
		c.sandboxedIO.Store(flag)

		// sandboxedExec stores whether subprocess exec is permitted. When a
		// context is sandboxed, exec is unconditionally blocked regardless of
		// the global ExecPermittedSetting. When sandboxing is lifted, restore
		// the global setting.
		if flag {
			c.sandboxedExec.Store(true)
		} else {
			c.sandboxedExec.Store(settings.GetBool(defs.ExecPermittedSetting))
		}

		c.symbols.SetAlways(defs.SandboxedIOSymbolName, flag)
		c.symbols.SetAlways(defs.SandboxedExecSymbolName, c.sandboxedExec.Load())

		// If we are enabling sandboxing and there isn't a sandbox path
		// defined, create one in the temp area.
		if sandboxPath := settings.Get(defs.SandboxPathSetting); sandboxPath == "" && flag {
			newPath := filepath.Join(os.TempDir(), "ego")
			_ = os.Mkdir(newPath, os.ModePerm)
			newPath = filepath.Join(newPath, "sandbox")
			_ = os.Mkdir(newPath, os.ModePerm)
			settings.SetDefault(defs.SandboxPathSetting, newPath)
		}
	}

	return c
}

// GetName returns the name of the module currently executing.
func (c *Context) GetName() string {
	if c.bc != nil {
		return c.bc.name
	}

	return defs.Main
}

// GetLine retrieves the current line number from the
// original source being executed. This is stored in the
// context every time an AtLine instruction is executed.
func (c *Context) GetLine() int {
	c.mux.RLock()
	defer c.mux.RUnlock()

	return c.line
}

// Set the extensions mode explicitly for the context.
func (c *Context) SetExtensions(b bool) *Context {
	c.extensions = b

	return c
}

// SetDebug turns debugging mode on or off for the current
// context. singleStep is set to the same value as b so that
// enabling the debugger always starts in step mode and disabling
// it clears step mode (CONTEXT-2 fix).
func (c *Context) SetDebug(b bool) *Context {
	c.debugging = b
	c.singleStep = b

	return c
}

func (c *Context) SetTrace(b bool) *Context {
	c.tracing = b

	return c
}

// SetFullSymbolScope sets the flag that indicates if a
// symbol table read can "see" a symbol outside the current
// function. The default is off, which means symbols are not
// visible outside the function unless they are in the global
// symbol table. If true, then a symbol can be read from any
// level of the symbol table parentage chain.
func (c *Context) SetFullSymbolScope(b bool) *Context {
	c.fullSymbolScope = b

	return c
}

// SetPC sets the program counter (PC) which indicates the
// next instruction number to execute.
func (c *Context) SetPC(pc int) *Context {
	c.programCounter = pc

	return c
}

// SetGlobal stores a value in a the global symbol table that is
// at the top of the symbol table chain.
func (c *Context) SetGlobal(name string, value any) error {
	return c.rootSymbols.Set(name, value)
}

// EnableConsoleOutput controls whether program output is sent directly to
// os.Stdout (flag=true, the default) or captured in an internal buffer
// (flag=false). Captured output can be retrieved with GetOutput.
func (c *Context) EnableConsoleOutput(flag bool) *Context {
	if ui.IsActive(ui.AppLogger) {
		ui.Log(ui.AppLogger, "app.console.enable", ui.A{
			"flag": flag})
	}

	if !flag {
		c.captureBuffer = &strings.Builder{}
		c.output = c.captureBuffer

		// We also store the writer object in the symbol table so the fmt package
		// can find it at runtime.
		c.symbols.SetAlways(defs.StdoutWriterSymbol, c.output)
	} else {
		c.captureBuffer = nil
		c.output = os.Stdout
	}

	return c
}

// GetOutput retrieves the captured program output accumulated since the last
// ClearOutput call. Returns an empty string when capture is not active.
func (c *Context) GetOutput() string {
	if c.captureBuffer != nil {
		return c.captureBuffer.String()
	}

	return ""
}

// ClearOutput resets the capture buffer to empty without disabling capture.
// It is a no-op when output capture is not active. This is used by the
// debugger to drain accumulated program output between debugger prompts.
func (c *Context) ClearOutput() {
	if c.captureBuffer != nil {
		c.captureBuffer.Reset()
	}
}

// Tracing returns the trace status of the current context. When
// tracing is on, each time an instruction is executed, the current
// instruction and the top few items on the stack are printed to
// the console.
func (c *Context) Tracing() bool {
	return ui.IsActive(ui.TraceLogger) || c.tracing
}

// SetTokenizer sets a tokenizer in the current context for use by
// tracing and debugging operations. This gives those functions
// access to the token stream used to compile the bytecode in this
// context.
func (c *Context) SetTokenizer(t *tokenizer.Tokenizer) *Context {
	c.tokenizer = t

	return c
}

// GetSource returns the stored source line (if any) in the
// current context.
func (c *Context) GetSource() string {
	return c.source
}

// GetTokenizer gets the tokenizer in the current context for
// tracing and debugging.
func (c *Context) GetTokenizer() *tokenizer.Tokenizer {
	return c.tokenizer
}

// AppendSymbols appends a symbol table to the current context.
// This is used to add in compiler maps, for example.
func (c *Context) AppendSymbols(s *symbols.SymbolTable) *Context {
	for _, name := range s.Names() {
		value, _ := s.Get(name)
		c.symbols.SetAlways(name, value)
	}

	return c
}

// SetByteCode attaches a new bytecode object to the current run context.
func (c *Context) SetByteCode(b *ByteCode) *Context {
	c.bc = b

	return c
}

// SetSingleStep enables or disables single-step mode. This has no
// effect if debugging is not active.
func (c *Context) SetSingleStep(b bool) *Context {
	c.singleStep = b

	return c
}

// SingleStep retrieves the current single-step setting for this
// context. This is used in the debugger to know how to handle
// break operations.
func (c *Context) SingleStep() bool {
	return c.singleStep
}

// SetStepOver determines if single step operations step over a
// function call, or step into it.
func (c *Context) SetStepOver(b bool) *Context {
	c.stepOver = b

	return c
}

// GetModuleName returns the name of the current module (typically
// the function name or program name).
func (c *Context) GetModuleName() string {
	if c.bc != nil {
		return c.bc.name
	}

	return defs.Main
}

// PopValue removes the top-most item from the stack and returns it.
// If the item was an immutable constant value, the value is unwrapped
// before returning it.
func (c *Context) Pop() (any, error) {
	v, err := c.PopWithoutUnwrapping()
	if err == nil {
		if c, ok := v.(data.Immutable); ok {
			v = c.Value
		}
	}

	return v, err
}

// Pop removes the top-most item from the stack. It also
// zeros out the stack entry item on the stack, which
// will make the item eligible for reclaimed by the Go native
// garbage collector.
func (c *Context) PopWithoutUnwrapping() (any, error) {
	if c.stackPointer <= 0 || len(c.stack) < c.stackPointer {
		return nil, c.runtimeError(errors.ErrStackUnderflow)
	}

	c.stackPointer = c.stackPointer - 1
	value := c.stack[c.stackPointer]
	c.stack[c.stackPointer] = nil

	return value, nil
}

// Helper function that retrieves the symbol table for the running context.
func (c *Context) GetSymbols() *symbols.SymbolTable {
	return c.symbols
}

// setConstant is a helper function to define a constant value.
func (c *Context) setConstant(name string, v any) error {
	return c.symbols.SetConstant(name, v)
}

// isConstant is a helper function to define a constant value.
func (c *Context) isConstant(name string) bool {
	return c.symbols.IsConstant(name)
}

// get is a helper function that retrieves a symbol value from the associated
// symbol table.
func (c *Context) get(name string) (any, bool) {
	return c.symbols.Get(name)
}

// set is a helper function that sets a symbol value in the associated
// symbol table.
func (c *Context) set(name string, value any) error {
	return c.symbols.Set(name, value)
}

// setAlways is a helper function that sets a symbol value in the associated
// symbol table.
func (c *Context) setAlways(name string, value any) {
	c.symbols.SetAlways(name, value)
}

// delete deletes a symbol from the current context.
func (c *Context) delete(name string) error {
	return c.symbols.Delete(name, false)
}

// create creates a symbol.
func (c *Context) create(name string) error {
	return c.symbols.Create(name)
}

// push puts a new items on the stack.
func (c *Context) push(value any) error {
	if c.stackPointer >= len(c.stack) {
		c.stack = append(c.stack, make([]any, growStackBy)...)
	}

	c.stack[c.stackPointer] = value
	c.stackPointer = c.stackPointer + 1

	if c.stackPointer > int(atomic.LoadInt32(&MaxStackSize)) {
		atomic.StoreInt32(&MaxStackSize, int32(c.stackPointer))
	}

	return nil
}

// checkType is a utility function used to determine if a given value could
// be stored in a named symbol, and coerces it if needed and permitted by the
// active type-enforcement mode:
//
//   - dynamic (NoTypeEnforcement): no check at all. Variables may freely
//     change type from one assignment to the next; this is the default.
//   - relaxed (RelaxedTypeEnforcement): the incoming value is always coerced
//     to match the *existing* variable's type, so the variable's type never
//     changes. An error is only returned when the value genuinely cannot be
//     converted (e.g. storing "abc" into an int variable) -- this mode does
//     automatically what strict mode requires the caller to do by hand with
//     an explicit cast.
//   - strict (StrictTypeEnforcement): follows Go's own assignability rules.
//     A non-constant value of a different type is always rejected -- the
//     caller must cast explicitly. A literal constant (e.g. "w = 5") may
//     convert implicitly, but only when the conversion loses no information,
//     mirroring Go's untyped-constant convertibility rule -- so "w = 3.7"
//     for an int w is still an error, even though "w = 3" (or "f = 5" for a
//     float64 f) is not.
//
// When the value is nil, or the named symbol does not yet exist (or holds
// symbols.UndefinedValue, i.e. is declared but not yet assigned), no check
// is performed and the value is returned unchanged. Likewise, a destination
// currently holding an interface{} value can accept any concrete type
// without coercion or error, in any enforcement mode.
func (c *Context) checkType(name string, value any) (any, error) {
	isConstant := false

	if constant, ok := value.(data.Immutable); ok {
		value = constant.Value
		isConstant = true
	}

	if c.typeStrictness == defs.NoTypeEnforcement || value == nil {
		return value, nil
	}

	// The map+chain lookup for the existing value is deliberately deferred
	// until after the two cheap early-outs above, so a dynamic-mode store
	// never pays for it. The remaining type-comparison logic is shared with
	// the slot-based store path (checkTypeSlot) via checkTypeCore.
	existingValue, ok := c.get(name)

	return c.checkTypeCore(value, existingValue, ok, isConstant)
}

// checkTypeSlot is the slot-based counterpart of checkType (see docs/SLOTS.md):
// it applies the same type-enforcement rules to a StoreSlot, reading the
// destination's current value directly from the slot bank instead of resolving
// it by name. The two share checkTypeCore for everything after the existing
// value has been obtained; only the way that existing value is fetched differs.
func (c *Context) checkTypeSlot(bank *symbols.SymbolTable, index int, value any) (any, error) {
	isConstant := false

	if constant, ok := value.(data.Immutable); ok {
		value = constant.Value
		isConstant = true
	}

	if c.typeStrictness == defs.NoTypeEnforcement || value == nil {
		return value, nil
	}

	existingValue, ok := bank.GetSlot(index)

	return c.checkTypeCore(value, existingValue, ok, isConstant)
}

// checkTypeCore holds the type-compatibility logic shared by checkType (name
// based) and checkTypeSlot (slot based). By the time it is called, value has
// already had any data.Immutable wrapper stripped (with isConstant recording
// whether it was wrapped) and the NoTypeEnforcement / nil-value early-outs have
// already been taken. exists reports whether existingValue was actually found;
// a not-found or nil destination accepts any value, as does one still holding
// symbols.UndefinedValue (declared but unassigned) or an interface{}.
func (c *Context) checkTypeCore(value, existingValue any, exists, isConstant bool) (any, error) {
	if !exists || existingValue == nil {
		return value, nil
	}

	if _, ok := existingValue.(symbols.UndefinedValue); ok {
		return value, nil
	}

	if data.TypeOf(existingValue).Kind() == data.InterfaceKind {
		return value, nil
	}

	if reflect.TypeOf(value) == reflect.TypeOf(existingValue) {
		return value, nil
	}

	switch c.typeStrictness {
	case defs.RelaxedTypeEnforcement:
		coerced, err := data.Coerce(value, existingValue)
		if err != nil {
			return nil, c.runtimeError(err)
		}

		return coerced, nil

	case defs.StrictTypeEnforcement:
		if !isConstant {
			return nil, c.runtimeError(errors.ErrInvalidVarType)
		}

		if !isNumericKind(data.KindOf(value)) || !isNumericKind(data.KindOf(existingValue)) {
			return nil, c.runtimeError(errors.ErrInvalidVarType)
		}

		// Reject the conversion if it lost information (e.g. 3.7 -> int),
		// exactly as Go rejects a truncating untyped-constant conversion at
		// compile time. This check is independent of the
		// ego.runtime.precision.error setting, which only governs explicit
		// runtime conversions (casts), not implicit constant assignment or
		// (as of BUG-68) constant adaptation in expressions, function
		// arguments, or return values -- see data.CoerceLossless, the shared
		// implementation of this same rule across all four boundaries.
		coerced, err := data.CoerceLossless(value, existingValue)
		if err != nil {
			return nil, c.runtimeError(err)
		}

		return coerced, nil
	}

	return nil, c.runtimeError(errors.ErrInvalidVarType)
}

// isNumericKind reports whether the given data.Kind is one of Ego's scalar
// numeric kinds (any integer width, signed or unsigned, either floating
// point width, or either complex width). Used by checkType's strict-mode
// literal-constant coercion path to decide whether an implicit conversion
// should even be attempted.
func isNumericKind(kind int) bool {
	switch kind {
	case data.ByteKind, data.Int8Kind, data.Int16Kind, data.UInt16Kind,
		data.Int32Kind, data.UInt32Kind, data.IntKind, data.UIntKind,
		data.Int64Kind, data.UInt64Kind, data.Float32Kind, data.Float64Kind,
		data.Complex64Kind, data.Complex128Kind:
		return true
	default:
		return false
	}
}

func (c *Context) Result() any {
	return c.result
}

func (c *Context) popSymbolTable() error {
	c.mux.Lock()
	defer c.mux.Unlock()

	if c.symbols.IsRoot() {
		if ui.IsActive(ui.SymbolLogger) {
			ui.Log(ui.SymbolLogger, "symbols.nil.parent", ui.A{
				"thread": c.threadID,
				"table":  c.symbols.Name})
		}

		return errors.ErrInternalCompiler.Context("Attempt to pop root table")
	}

	if c.symbols == c.symbols.Parent() {
		return errors.ErrInternalCompiler.Context("Symbol Table Cycle Error")
	}

	c.symbols.DiscardEphemera()

	name := c.symbols.Name
	c.symbols = c.symbols.Parent()

	for strings.HasPrefix(c.symbols.Name, "pkg func ") {
		if c.symbols.IsRoot() {
			break
		}

		c.symbols = c.symbols.Parent()
	}

	if ui.IsActive(ui.SymbolLogger) {
		ui.Log(ui.SymbolLogger, "symbols.pop.table", ui.A{
			"thread": c.threadID,
			"name":   name,
			"child":  c.symbols.Name})
	}

	return nil
}

// unwrapConstant is a utility function that unwraps a constant
// value. If the value isn't a constant, it returns the original
// value.
func (c *Context) unwrapConstant(v any) any {
	if constant, ok := v.(data.Immutable); ok {
		return constant.Value
	}

	return v
}
