package dsns

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/tucats/ego/internal/cli/settings"
	"github.com/tucats/ego/internal/cli/ui"
	"github.com/tucats/ego/internal/dbpool"
	"github.com/tucats/ego/internal/defs"
	"github.com/tucats/ego/internal/errors"
	"github.com/tucats/ego/internal/util"
)

type fileService struct {
	Path  string
	lock  sync.Mutex
	dirty bool
	Data  map[string]defs.DSN
	Auth  map[string]DSNAction
}

const jsonHeader = `
// This file contains the DSN descriptors. This file was last updated at %s
// 
// *** DO NOT EDIT THIS FILE. IT IS AUTOMATICALLY GENERATED. ***
`

// NewFileService creates a new file-based DSN service. If the userDatabaseFile
// is "memory" then an in-memory service is created. Otherwise, the file is read
// and the contents are used to initialize the service.
func NewFileService(userDatabaseFile string) (dsnService, error) {
	if userDatabaseFile == defs.MemoryProvider {
		userDatabaseFile = ""
	}

	svc := &fileService{
		Path: userDatabaseFile,
		Data: map[string]defs.DSN{},
		Auth: map[string]DSNAction{},
	}

	if userDatabaseFile != "" {
		svcObject := fileService{}

		if b, err := ui.ReadJSONFile(userDatabaseFile); err == nil {
			if key := settings.Get(defs.LogonUserdataKeySetting); key != "" {
				if r, err := util.Decrypt(string(b), key); err != nil {
					return svc, errors.New(err)
				} else {
					b = []byte(r)
				}
			}

			if err = json.Unmarshal(b, &svcObject); err != nil {
				return svc, errors.New(err)
			}

			svc.Data = svcObject.Data
			svc.Auth = svcObject.Auth

			ui.Log(ui.AuthLogger, "auth.file.size", ui.A{
				"size": len(svc.Data)})
		}
	}

	if len(svc.Data) == 0 {
		svc.Data = map[string]defs.DSN{}
		svc.dirty = true

		if svc.Path == "" {
			ui.Log(ui.AuthLogger, "auth.dsn.memory", nil)
		} else {
			ui.Log(ui.AuthLogger, "auth.dsn.file", ui.A{
				"path": svc.Path,
			})
		}
	}

	return svc, nil
}

// ListDSNS lists the DSNs stored in the file, keyed by name. The returned
// map is a fresh copy, not the service's own internal Data map -- matching
// databaseService.ListDSNS's contract, since ListDSNHandler mutates the map
// it gets back (deleting entries the caller isn't authorized to see) and
// handing out f.Data directly would let that delete corrupt the live store.
// Each entry's Password is redacted for the same reason
// databaseService.ListDSNS redacts it: this is a list endpoint, and the
// stored value (even though it's the encrypted ciphertext, not plaintext)
// has no business being echoed back here.
func (f *fileService) ListDSNS(session int, user string) (map[string]defs.DSN, error) {
	r := make(map[string]defs.DSN, len(f.Data))

	for name, dsn := range f.Data {
		dsn.Password = defs.ElidedPassword
		r[name] = dsn
	}

	return r, nil
}

func (f *fileService) ReadDSN(session int, user, name string, doNotLog bool) (defs.DSN, error) {
	var err error

	dsn, ok := f.Data[name]
	if !ok {
		err = errors.ErrNoSuchDSN.Context(name)
	}

	return dsn, err
}

func (f *fileService) WriteDSN(session int, user string, dsn defs.DSN) error {
	_, found := f.Data[dsn.Name]
	if !found {
		dsn.ID = uuid.NewString()
	}

	f.Data[dsn.Name] = dsn
	f.dirty = true

	// See the identical call in databaseService.WriteDSN (dsn_sqldb.go): a
	// cached connection pool for this DSN name must not keep serving
	// whatever host/database was in effect before this write.
	dbpool.Evict(dsn.Name)

	if found {
		ui.Log(ui.AuthLogger, "auth.dsn.update", ui.A{
			"session": session,
			"name":    dsn.Name})
	} else {
		ui.Log(ui.AuthLogger, "auth.dsn.create", ui.A{
			"session": session,
			"name":    dsn.Name})
	}

	return f.Flush()
}

func (f *fileService) DeleteDSN(session int, user, name string) error {
	u, err := f.ReadDSN(session, user, name, false)
	if err == nil {
		f.dirty = true

		delete(f.Data, u.Name)
		f.revokeAllLocked(u.Name)

		// See the identical call in databaseService.DeleteDSN (dsn_sqldb.go).
		dbpool.Evict(u.Name)

		ui.Log(ui.AuthLogger, "auth.dsn.delete", ui.A{
			"session": session,
			"name":    u.Name})
	}

	return f.Flush()
}

// RevokeAllDSN removes every user's auth record for the named DSN, without
// touching the DSN record itself. Used both by DeleteDSN (as part of
// deleting the DSN entirely) and by UpdateDSNHandler when a DSN
// transitions from Restricted to unrestricted (DATA-SECURITY-2.md finding
// #7): the permission records that governed access under the old
// Restricted state have no meaning once the DSN is open to everyone, and
// leaving them behind would let them silently reactivate if the DSN were
// ever restricted again.
func (f *fileService) RevokeAllDSN(session int, name string) error {
	// revokeAllLocked must run unconditionally on the left of this
	// assignment -- "f.dirty || f.revokeAllLocked(name)" would short-
	// circuit and never call it at all once f.dirty was already true from
	// an earlier write in the same request.
	changed := f.revokeAllLocked(name)
	f.dirty = f.dirty || changed

	return f.Flush()
}

// revokeAllLocked removes every user's auth record for the named DSN from
// f.Auth in place. It returns true if anything was actually removed, so
// callers only mark the service dirty when there was a real change.
func (f *fileService) revokeAllLocked(name string) bool {
	changed := false

	for key := range f.Auth {
		parts := strings.SplitN(key, "|", 2)
		if len(parts) == 2 && parts[1] == name {
			delete(f.Auth, key)

			changed = true
		}
	}

	return changed
}

// RevokeAllDSNForUser removes every auth record for the named user, across
// all DSNs. Used when a user account is deleted, so that stale grants don't
// linger (and potentially reactivate) if the username is ever reused.
func (f *fileService) RevokeAllDSNForUser(session int, user string) error {
	changed := false

	for key := range f.Auth {
		parts := strings.SplitN(key, "|", 2)
		if len(parts) == 2 && parts[0] == user {
			delete(f.Auth, key)

			changed = true
		}
	}

	f.dirty = f.dirty || changed

	return f.Flush()
}

// Flush writes the file-based data to a json file. This operation is not
// done if there were no changes to the database, or there is not a database
// file name given.
func (f *fileService) Flush() error {
	if !f.dirty || f.Path == "" {
		return nil
	}

	// Serialize the flush operation.
	f.lock.Lock()
	defer f.lock.Unlock()

	// Convert the database to a json string
	b, err := json.MarshalIndent(f, "", "   ")
	if err != nil {
		return errors.New(err)
	}

	if key := settings.Get(defs.LogonUserdataKeySetting); key != "" {
		r, err := util.Encrypt(string(b), key)
		if err != nil {
			return err
		}

		b = []byte(r)
	}

	// Write to the database file. Create a new file descriptor for the output file.
	fd, err := os.OpenFile(f.Path, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0600)
	if err != nil {
		return errors.New(err)
	}

	defer fd.Close()

	// Form the JSON header text followed by the JSON data.
	text := fmt.Sprintf(jsonHeader, time.Now().Format(time.RFC3339))

	_, err = fd.WriteString(text)
	if err != nil {
		return errors.New(err)
	}

	_, err = fd.Write(b)
	if err == nil {
		f.dirty = false

		ui.Log(ui.AuthLogger, "auth.dsn.flush", nil)
	} else {
		err = errors.New(err)
	}

	return err
}

// Close releases any resources held by this service. The file-based service
// doesn't keep a persistent file handle open between operations (Flush opens
// and closes its own file descriptor each time -- see above), so there is
// nothing to release here beyond making sure any pending changes are
// written out first, exactly like a well-behaved io.Closer should.
func (f *fileService) Close() error {
	return f.Flush()
}

// AuthDSN determines if the given username is allowed to access the
// named DSN. This will involve lookups to the auth map to determine
// if the DSN is restricted, and if so, is this user on the list?
//
// DATA-SECURITY-2.md finding #6: this used to skip the Restricted check
// entirely, so an unrestricted DSN was gated exactly like a restricted one
// -- any caller without an explicit Auth entry was denied, inverting the
// documented default that an unrestricted DSN "is not gated by Ego in any
// way." Mirrors databaseService.AuthDSN's early return.
func (f *fileService) AuthDSN(session int, user, name string, action DSNAction) bool {
	dsn, err := f.ReadDSN(session, user, name, true)
	if err != nil {
		return false
	}

	if !dsn.Restricted {
		return true
	}

	key := user + "|" + name

	if value, found := f.Auth[key]; found {
		return (value & action) != DSNNoAccess
	}

	return false
}

// GrantDSN sets the allowed actions for an item. The grant flag indicates if the
// value is granted versus revoked.
func (f *fileService) GrantDSN(session int, user, name string, action DSNAction, grant bool) error {
	// Does this DSN even exist? If not, this is an error -- matching
	// databaseService.GrantDSN, which refuses to create an orphaned auth
	// record for a DSN that was never created (or already deleted).
	dsn, found := f.Data[name]
	if !found {
		return errors.ErrNoSuchDSN.Context(name)
	}

	key := user + "|" + name

	if value, found := f.Auth[key]; found {
		if grant {
			value = value | action
		} else {
			value = value &^ action
		}

		f.Auth[key] = value
	} else {
		if grant {
			f.Auth[key] = action
		} else {
			f.Auth[key] = DSNNoAccess
		}
	}

	// If the DSN was not previously marked as restricted, mark it now so
	// future access uses the auth map for authorization checks -- matching
	// databaseService.GrantDSN's identical side effect.
	if !dsn.Restricted {
		dsn.Restricted = true
		f.Data[name] = dsn

		ui.Log(ui.AuthLogger, "auth.dsn.restrict", ui.A{
			"session": session,
			"name":    name})
	}

	f.dirty = true

	return f.Flush()
}

func (f *fileService) Permissions(session int, user, name string) (map[string]DSNAction, error) {
	result := map[string]DSNAction{}

	d, err := f.ReadDSN(session, user, name, true)
	if err != nil {
		return result, err
	}

	if !d.Restricted {
		return result, nil
	}

	for key, auth := range f.Auth {
		parts := strings.Split(key, "|")
		if parts[1] == name {
			result[parts[0]] = auth
		}
	}

	return result, nil
}
