package compiler

import (
	"fmt"
	"sync"

	"github.com/tucats/ego/internal/cli/ui"
	"github.com/tucats/ego/internal/language/bytecode"
	"github.com/tucats/ego/internal/language/data"
	"github.com/tucats/ego/internal/defs"
	"github.com/tucats/ego/internal/errors"
	"github.com/tucats/ego/internal/language/tokenizer"
)

// Define the types of for loops we can compile. This determines how to
// handle increment and end-of-range tests.
type runtimeLoopType int

const (
	indexLoopType       runtimeLoopType = 1
	rangeLoopType       runtimeLoopType = 2
	forLoopType         runtimeLoopType = 3
	conditionalLoopType runtimeLoopType = 4
)

// These are used to generate index names when needed for range loops when the "_"
// variable is used.
var indexNameLock = &sync.Mutex{}
var indexNameCounter int

// ---------------------------------------------------------------------------
// BUG-30: per-iteration loop variables (Go 1.22+ semantics)
//
// Background for readers unfamiliar with this Go language change: before Go
// 1.22, a "for" loop's index/value variable(s) were a single variable shared
// by every trip through the loop. This was a well-known source of bugs
// whenever a closure was created inside the loop body and captured that
// variable, because *every* closure ended up sharing the exact same
// variable - so by the time any of the closures actually ran, they all saw
// whatever value the variable held when the loop finished, not the value it
// had when each closure was created. Go 1.22 changed the language spec so
// that each iteration gets its own fresh copy of the variable instead.
//
// Ego's compiler represents a loop with a single "outer" scope, pushed once
// before the loop starts and popped once after it ends (see compileFor,
// which emits the very first PushScope). The loop's index/value variable(s)
// live in that outer scope, so - before this fix - they really were one
// variable shared by every iteration, matching pre-1.22 Go instead of
// today's Go.
//
// The fix does NOT change where the "outer" variable lives (the increment
// and condition clauses of a classic "for i := 0; i < n; i++" loop, and the
// RangeNext bytecode for a "for k, v := range x" loop, continue to read and
// write that one outer variable exactly as before). Instead, it arranges for
// the loop *body* to run against its own fresh copy every time: a small
// "prologue" is spliced in as the first thing inside the body's own scope
// (which - unlike the loop's outer scope - already IS recreated fresh every
// iteration, because the body's PushScope instruction is re-executed each
// time the loop branches back to it) that copies the outer variable's
// current value into a same-named variable in that fresh scope. Any closure
// created anywhere in the body captures THIS scope, and therefore this
// iteration's own copy, not the loop's single outer variable.
// ---------------------------------------------------------------------------

// loopVariablePrologue returns the bytecode that gives the body of a single
// loop iteration its own copy of the named loop-control variable. It must be
// spliced in as the very first instructions inside the body's scope (see
// compileForBody), before any user statement runs.
//
// Generated bytecode, in order:
//
//	Load <name>          // read the CURRENT value from the enclosing scope
//	                      // (the loop's single, persistent "outer" variable)
//	SymbolCreate <name>   // declare a brand new variable with the SAME name,
//	                      // in the scope we are currently in (the body's own
//	                      // scope, just entered). Because a scope search
//	                      // always looks at the innermost scope first, this
//	                      // new variable now shadows the outer one for the
//	                      // rest of the loop body.
//	Store <name>          // ...and give the new variable the value that was
//	                      // just loaded from the outer one.
//
// Because compileForBody's PushScope executes again every time the loop
// branches back to the top (it is ordinary loop-body bytecode, not something
// that runs once at compile time), this whole sequence - and therefore the
// variable it creates - is genuinely brand new on every iteration.
func loopVariablePrologue(name string) *bytecode.ByteCode {
	b := bytecode.New("loop variable copy-in")
	b.Emit(bytecode.Load, name)
	b.Emit(bytecode.SymbolCreate, name)
	b.Emit(bytecode.Store, name)

	return b
}

// loopVariableEpilogue returns the bytecode that copies a per-iteration loop
// variable's value back out to the loop's outer, persistent variable before
// the per-iteration scope holding it is destroyed. Without this, a loop body
// that intentionally reassigns its own loop-control variable to influence
// later iterations - a legal, if uncommon, Go pattern such as
// "for i := 0; i < 10; i++ { if skip { i += 5 } }" - would have that
// reassignment silently discarded, because it would only ever change the
// per-iteration copy, never the variable the increment/condition clauses
// actually read.
//
// Generated bytecode, in order:
//
//	Load <name>    // read the per-iteration copy's current (possibly
//	               // body-modified) value. This resolves to the shadowing
//	               // (inner) variable, because we are still inside the
//	               // per-iteration scope created by loopVariablePrologue.
//	PopScope       // leave the per-iteration scope. "<name>" now resolves to
//	               // the outer, persistent loop-control variable again,
//	               // since the shadowing copy that hid it no longer exists.
//	Store <name>   // ...and overwrite the outer variable with the value
//	               // just loaded, before the increment/condition clauses
//	               // run against it.
//
// Only compileForBody's caller may use this: because the epilogue itself
// performs the PopScope that closes the per-iteration scope, compileForBody
// must NOT also emit its own closing PopScope when an epilogue is supplied
// (it would double-pop). See compileForBody.
//
// KNOWN LIMITATION (see docs/ISSUES.md, BUG-30): this epilogue only runs
// when the loop body finishes normally, by falling off the end. A "break" or
// "continue" - including one nested inside an "if"/"switch"/"try" block
// inside the loop body - branches directly out of the body and skips this
// epilogue entirely, exactly as it already skips over any ordinary block's
// closing PopScope today (a pre-existing characteristic of how break/continue
// interact with nested scopes in this compiler, not something newly
// introduced here). Practically, this means a same-iteration reassignment of
// the loop variable is not carried forward to the next iteration if that
// same iteration also used break or continue. This does NOT affect the
// primary fix: closures still correctly capture their own per-iteration copy
// of the variable no matter how the iteration ends, because
// loopVariablePrologue always runs first, before any user code (including
// any break/continue) executes.
func loopVariableEpilogue(name string) *bytecode.ByteCode {
	b := bytecode.New("loop variable copy-out")
	b.Emit(bytecode.Load, name)
	b.Emit(bytecode.PopScope)
	b.Emit(bytecode.Store, name)

	return b
}

// compileForBody compiles a for-loop's body block (the caller must not have
// consumed the opening "{" yet), optionally splicing prologue and/or
// epilogue bytecode immediately inside the body's own scope: prologue runs
// first, before any user statement; epilogue runs last, after every user
// statement, while the scope is still open.
//
// This is deliberately a near-duplicate of compileBlock/compileRequiredBlock
// rather than a shared, parameterized version of them: those two functions
// are used all over the compiler (if, switch, try, function bodies, ...) and
// adding loop-specific parameters to them would obscure what they do for
// every other caller. Keeping the splicing logic local to for.go, which is
// the only place that needs it, keeps the common case (compileBlock with no
// splicing) simple to read.
//
// If epilogue is nil, this function emits the ordinary closing PopScope
// itself, exactly like compileRequiredBlock. If epilogue is non-nil, it MUST
// contain its own PopScope (see loopVariableEpilogue) - this function will
// not add a second one.
func (c *Compiler) compileForBody(prologue, epilogue *bytecode.ByteCode) error {
	// An empty body ("for i := range x {}") has no statements that could
	// possibly create a closure over the loop variable, or reassign it.
	// Skip the scope (and the prologue/epilogue) entirely, matching
	// compileRequiredBlock's own handling of the empty-block token.
	if c.t.IsNext(tokenizer.EmptyBlockToken) {
		return nil
	}

	if !c.t.IsNext(tokenizer.BlockBeginToken) {
		return c.compileError(errors.ErrMissingBlock)
	}

	c.blockDepth++
	c.PushSymbolScope()
	c.b.Emit(bytecode.PushScope)

	if prologue != nil {
		c.b.Append(prologue)
	}

	for !c.t.IsNext(tokenizer.BlockEndToken) {
		if err := c.compileStatement(); err != nil {
			return err
		}

		// The tokenizer may insert semicolons between statements; skip them.
		_ = c.t.IsNext(tokenizer.SemicolonToken)

		if c.t.AtEnd() {
			return c.compileError(errors.ErrMissingEndOfBlock)
		}
	}

	if epilogue != nil {
		c.b.Append(epilogue)
	} else {
		c.b.Emit(bytecode.PopScope)
	}

	c.blockDepth--

	return c.PopSymbolScope()
}

// compileFor compiles the loop statement. This has four syntax types that
// can be specified.
//
//  1. There are three clauses which are separated by tokenizer.SemicolonToken, followed
//     by a statement or block that is run as described by the loop
//     index variable conditions.
//
//  2. There can be a range operation which creates an implied loop
//     using each member of the array or struct.
//
//  3. There can be a simple conditional expression. The loop runs
//     until the condition expression is false. The condition is
//     tested at the start of every loop, so a condition that is
//     initially false never runs the loop
//
//  4. A for{} with no condition, loop, or range expression.
//     this form _requires_ that there be at least one break
//     statement inside the loop, which algorithmically stops
//     the loop
func (c *Compiler) compileFor() error {
	if c.t.AnyNext(tokenizer.SemicolonToken, tokenizer.EndOfTokens) {
		return c.compileError(errors.ErrMissingExpression)
	}

	if c.t.IsNext(tokenizer.EmptyBlockToken) {
		return c.compileError(errors.ErrLoopExit)
	}

	c.b.Emit(bytecode.PushScope, bytecode.ForScope)

	// Is this a for{} with no conditional or iterator?
	if c.t.Peek(1).Is(tokenizer.BlockBeginToken) {
		return c.simpleFor()
	}

	// Is this the two-value range thing?
	indexName := c.t.Peek(1)
	valueName := tokenizer.EmptyToken

	if indexName.IsIdentifier() && c.t.Peek(2).Is(tokenizer.CommaToken) {
		c.t.Advance(2)
		valueName = c.t.Peek(1)
	}

	indexNameSpelling := c.normalize(indexName.Spelling())
	valueNameSpelling := c.normalize(valueName.Spelling())

	// if not an lvalue, assume conditional mode
	if !c.isAssignmentTarget() {
		return c.conditionalFor()
	}

	indexStore, err := c.assignmentTarget()
	if err != nil {
		return err
	}

	// Because we put a marker on the stack during the
	// assignment, whenever we're done with the loop,
	// drop the marker.
	defer c.b.Emit(bytecode.DropToMarker)

	if !c.t.AnyNext(tokenizer.DefineToken, tokenizer.AssignToken) {
		return c.compileError(errors.ErrMissingLoopAssignment)
	}

	// Do we compile a range?
	if c.t.IsNext(tokenizer.RangeToken) {
		return c.rangeFor(indexNameSpelling, valueNameSpelling)
	}

	// Nope, must be an old-school iteration form.
	return c.iterationFor(indexNameSpelling, valueNameSpelling, indexStore)
}

// loopStackPush creates a new loop context and adds it to the top of the
// loop stack. This stack retains information about the loop type and
// the accumulation of breaks and continues that are specified within
// this loop body. A break or continue _only_ applies to the loop scope
// in which it occurs.
//
// If a label was set on the compiler via a "label: for" statement,
// loopStackPush consumes it so it is attached to exactly this loop.
func (c *Compiler) loopStackPush(loopType runtimeLoopType) {
	label := c.pendingLabel
	c.pendingLabel = ""

	c.loops = &loop{
		loopType:  loopType,
		label:     label,
		breaks:    make([]int, 0),
		continues: make([]int, 0),
		parent:    c.loops,
	}
}

// loopStackPop discards the top-most loop context on the loop stack.
func (c *Compiler) loopStackPop() {
	if c.loops != nil {
		c.loops = c.loops.parent
	} else {
		ui.Log(ui.CompilerLogger, "trace.loop.empty", nil)
	}
}

// Compile a simple for{} loop with no conditional or range. The
// loop body must contain a break statement or an error is reported.
func (c *Compiler) simpleFor() error {
	// Make a new scope and emit the test expression.
	c.loopStackPush(forLoopType)

	// Remember top of loop. There is no looping or condition code associated
	// with the top of the loop.
	b1 := c.b.Mark()

	// Compile loop body
	if err := c.compileRequiredBlock(false); err != nil {
		return err
	}

	// Branch back to start of loop
	c.b.Emit(bytecode.Branch, b1)

	for _, fixAddr := range c.loops.continues {
		_ = c.b.SetAddress(fixAddr, b1)
	}

	// Update any break statements. If there are no breaks, this is an illegal loop construct
	if len(c.loops.breaks) == 0 {
		return c.compileError(errors.ErrLoopExit)
	}

	for _, fixAddr := range c.loops.breaks {
		_ = c.b.SetAddressHere(fixAddr)
	}

	c.loopStackPop()

	return nil
}

// Compile a conditional for-loop that runs as long as the condition
// is true.
func (c *Compiler) conditionalFor() error {
	bc, err := c.Expression(true)
	if err != nil {
		return c.compileError(errors.ErrMissingForLoopInitializer)
	}

	// Make a point of seeing if this is a constant value, which
	// will require a break statement. We check to see if the test
	// loads any symbols or calls any functions.
	ops := bc.Opcodes()
	isConstant := true

	for _, b := range ops {
		if b.Operation == bytecode.Load ||
			b.Operation == bytecode.LoadIndex ||
			b.Operation == bytecode.Call ||
			b.Operation == bytecode.LocalCall ||
			b.Operation == bytecode.Member {
			isConstant = false

			break
		}
	}

	// Make a new scope and emit the test expression.
	c.loopStackPush(conditionalLoopType)

	// Remember top of loop and generate test
	b1 := c.b.Mark()

	c.b.Append(bc)

	b2 := c.b.Mark()

	c.b.Emit(bytecode.BranchFalse, 0)

	// Compile loop body
	opCount := c.b.Mark()
	statementCount := c.statementCount

	if err = c.compileRequiredBlock(false); err != nil {
		return err
	}

	// If we didn't emit anything other than
	// the AtLine then this is an invalid loop
	if c.b.Mark() <= opCount+1 {
		return c.compileError(errors.ErrLoopBody)
	}

	// Uglier test, but also needs doing. If there was a statement, but
	// it was a block that did not contain any statements, also empty body.
	wasBlock := c.b.Opcodes()[len(c.b.Opcodes())-1]
	if wasBlock.Operation == bytecode.PopScope && statementCount == c.statementCount {
		return c.compileError(errors.ErrLoopBody)
	}

	// Branch back to start of loop
	c.b.Emit(bytecode.Branch, b1)

	for _, fixAddr := range c.loops.continues {
		_ = c.b.SetAddress(fixAddr, b1)
	}

	// Update the loop exit instruction, and any breaks
	_ = c.b.SetAddressHere(b2)

	if isConstant && len(c.loops.breaks) == 0 {
		return c.compileError(errors.ErrLoopExit)
	}

	for _, fixAddr := range c.loops.breaks {
		_ = c.b.SetAddressHere(fixAddr)
	}

	c.b.Emit(bytecode.PopScope)
	c.loopStackPop()

	return nil
}

// Compile a for-loop that is expressed by a range. The index variable name
// and value variable names are provided. If not specified by the user, they
// are empty strings.
func (c *Compiler) rangeFor(indexName, valueName string) error {
	c.loopStackPush(rangeLoopType)

	// For a range, the index and value targets must be simple names, and cannot
	// be real lvalues. The actual thing we range is on the stack.
	if err := c.emitExpression(); err != nil {
		return err
	}

	if indexName != defs.DiscardedVariable {
		c.DefineSymbol(indexName)
	} else {
		indexName = generateIndexName("idx")
	}

	if valueName != defs.DiscardedVariable {
		c.DefineSymbol(valueName)
	} else {
		valueName = generateIndexName("val")
	}

	c.b.Emit(bytecode.RangeInit, indexName, valueName)

	// Remember top of loop
	b1 := c.b.Mark()

	// Get new index and value. Destination is as-yet unknown.
	c.b.Emit(bytecode.RangeNext, 0)

	// BUG-30 fix: RangeNext (above) always updates the index/value names in
	// this loop's single outer scope, in place, on every iteration - so
	// without a fresh per-iteration copy, a closure created in the body
	// would capture that one ever-changing variable instead of a snapshot of
	// its value for this particular iteration. Build a prologue that copies
	// each range variable actually in use into the body's own (freshly
	// recreated every iteration) scope. There is no epilogue: unlike a
	// classic "for" loop's index, reassigning a range loop's index or value
	// variable inside the body has no effect on which element is visited
	// next in Go, so there is nothing to copy back out.
	prologue := bytecode.New("range variable copy-in")

	if indexName != "" {
		prologue.Append(loopVariablePrologue(indexName))
	}

	if valueName != "" {
		prologue.Append(loopVariablePrologue(valueName))
	}

	// Loop body
	if err := c.compileForBody(prologue, nil); err != nil {
		return err
	}

	// Make note of the loop end point where continues fall.
	b3 := c.b.Mark()

	// Branch back to start of loop
	c.b.Emit(bytecode.Branch, b1)

	for _, fixAddr := range c.loops.continues {
		_ = c.b.SetAddress(fixAddr, b3)
	}

	_ = c.b.SetAddressHere(b1)

	for _, fixAddr := range c.loops.breaks {
		_ = c.b.SetAddressHere(fixAddr)
	}

	c.loopStackPop()
	c.b.Emit(bytecode.PopScope)

	return nil
}

// Compile a for loop using iterations with initializer, conditional, and
// iterator expressions before the function body.
func (c *Compiler) iterationFor(indexName, valueName string, indexStore *bytecode.ByteCode) error {
	// Normal numeric loop conditions. At this point there should not be an index
	// variable defined.
	if indexName == tokenizer.EmptyToken.Spelling() && valueName != tokenizer.EmptyToken.Spelling() {
		return c.compileError(errors.ErrInvalidLoopIndex)
	}

	c.loopStackPush(indexLoopType)

	// The expression is the initial value of the loop.
	initializerCode, err := c.Expression(true)
	if err != nil {
		return err
	}

	c.b.Append(initializerCode)
	c.b.Append(indexStore)

	if !c.t.IsNext(tokenizer.SemicolonToken) {
		return c.compileError(errors.ErrMissingSemicolon)
	}

	// Now get the condition clause that tells us if the loop
	// is still executing.
	condition, err := c.Expression(true)
	if err != nil {
		return err
	}

	if !c.t.IsNext(tokenizer.SemicolonToken) {
		return c.compileError(errors.ErrMissingSemicolon)
	}

	// Finally, get the clause that updates something
	// (nominally the index) to eventually trigger the
	// loop condition.
	incrementStore, err := c.assignmentTarget()
	if err != nil {
		return err
	}

	// Check for increment or decrement operators
	autoMode := bytecode.Load

	if c.t.Peek(1).Is(tokenizer.IncrementToken) {
		autoMode = bytecode.Add
	}

	if c.t.Peek(1).Is(tokenizer.DecrementToken) {
		autoMode = bytecode.Sub
	}

	var incrementCode *bytecode.ByteCode

	// If increment mode was used, then the increment is just to add (or subtract)
	// 1 from the value.  Two forms are handled:
	//
	//  1. Simple variable increment: for i := 0; i < n; i++
	//     The first instruction of incrementStore is Store "i", so we just emit
	//     Load "i", Push 1, Add/Sub into incrementCode.
	//
	//  2. Qualified lvalue increment: for a[0] := 0; ...; a[0]++
	//     The incrementStore has a load-path + StoreIndex structure.  We copy
	//     the load path and emit LoadIndex to read the current value, then
	//     apply the arithmetic.  The full incrementStore is appended afterward
	//     by the caller to write the result back.
	if autoMode != bytecode.Load {
		incrementCode = bytecode.New("auto")

		// Inspect the first instruction of the lvalue store code to decide
		// whether this is a simple variable or a qualified lvalue.
		firstInstr := incrementStore.Instruction(0)
		isSimple := firstInstr != nil && firstInstr.Operation == bytecode.Store

		if isSimple {
			// Simple variable increment (the common case: i++ in a for loop).
			t := data.String(firstInstr.Operand)

			if err := c.ReferenceSymbol(t); err != nil {
				return err
			}

			incrementCode.Emit(bytecode.Load, t)
		} else {
			// Qualified lvalue increment (e.g., a[i]++ or s.count++ in a for clause).
			//
			// The incrementStore structure is:
			//   [0]     Load "base"    — load the container
			//   [1..n-3] <index exprs> — push each index
			//   [n-2]   StoreIndex     — write back (patched from LoadIndex)
			//   [n-1]   DropToMarker   — cleanup
			//
			// Build incrementCode with the load path + LoadIndex so that the
			// current element value ends up on the stack ready for arithmetic.
			storeInstrIdx := incrementStore.Mark() - 2
			storeInstr := incrementStore.Instruction(storeInstrIdx)

			if storeInstr == nil || storeInstr.Operation != bytecode.StoreIndex {
				// Not a recognized lvalue form for auto-increment.
				return c.compileError(errors.ErrInvalidAuto)
			}

			// Copy the navigation instructions (Load base + index exprs).
			for i := 0; i < storeInstrIdx; i++ {
				instr := incrementStore.Instruction(i)
				incrementCode.Emit(instr.Operation, instr.Operand)
			}

			// Read the current element value.  The operand mirrors that of
			// StoreIndex: nil pops the index from stack; non-nil uses a folded
			// constant directly.
			incrementCode.Emit(bytecode.LoadIndex, storeInstr.Operand)
		}

		// Push 1 and apply the Add or Sub operation.
		incrementCode.Emit(bytecode.Push, 1)
		incrementCode.Emit(autoMode)
		c.t.Advance(1)
	} else {
		// Not auto-increment/decrement, so must be a legit assignment and expression
		if !c.t.IsNext(tokenizer.AssignToken) {
			return c.compileError(errors.ErrMissingEqual)
		}

		incrementCode, err = c.Expression(true)
		if err != nil {
			return err
		}
	}

	// Top of loop body starts here
	b1 := c.b.Mark()

	// Emit the test condition
	c.b.Append(condition)

	b2 := c.b.Mark()

	c.b.Emit(bytecode.BranchFalse, 0)

	// BUG-30 fix: give this loop's body a fresh, per-iteration copy of the
	// loop counter, so that a closure created in the body captures this
	// iteration's value instead of the one persistent variable the
	// increment/condition clauses above read and write (see the block
	// comment above loopVariablePrologue for the full explanation).
	//
	// This only applies when the loop counter is a plain named variable.
	// indexStore's shape depends on whether the initializer used ":=" or "=":
	//
	//	for i := 0; ...   ->  [0] SymbolCreate "i"   [1] Store "i"
	//	for i = 0; ...    ->  [0] Store "i"
	//
	// (this differs from incrementStore's simple-vs-qualified check further
	// below, which never sees a SymbolCreate because "i++" cannot declare a
	// new variable). A qualified lvalue counter (e.g.
	// "for a[0] = 0; a[0] < n; a[0]++") starts with a Load of the base
	// container instead, and has no single variable name to copy into a
	// shadow scope, so it is left exactly as before.
	var prologue, epilogue *bytecode.ByteCode

	isSimpleIndex := false

	if firstInstr := indexStore.Instruction(0); firstInstr != nil {
		switch firstInstr.Operation {
		case bytecode.Store:
			isSimpleIndex = true

		case bytecode.SymbolCreate:
			if second := indexStore.Instruction(1); second != nil && second.Operation == bytecode.Store {
				isSimpleIndex = true
			}
		}
	}

	if isSimpleIndex {
		prologue = loopVariablePrologue(indexName)
		epilogue = loopVariableEpilogue(indexName)
	}

	// Loop body goes next
	if err = c.compileForBody(prologue, epilogue); err != nil {
		return err
	}

	// Mark the position where continue branches land: just before the
	// increment code so that the loop variable is updated before the
	// condition is re-evaluated.
	continueTarget := c.b.Mark()

	// Emit increment code, and loop. Finally, mark the exit location from
	// the condition test for the loop.
	c.b.Append(incrementCode)
	c.b.Append(incrementStore)
	c.b.Emit(bytecode.Branch, b1)
	_ = c.b.SetAddressHere(b2)

	for _, fixAddr := range c.loops.continues {
		_ = c.b.SetAddress(fixAddr, continueTarget)
	}

	for _, fixAddr := range c.loops.breaks {
		_ = c.b.SetAddressHere(fixAddr)
	}

	c.b.Emit(bytecode.PopScope)
	c.loopStackPop()

	return nil
}

// findLoop walks the loop stack looking for a loop with the given label.
// Returns nil if no labeled loop with that name is found.
func (c *Compiler) findLoop(label string) *loop {
	for l := c.loops; l != nil; l = l.parent {
		if l.label == label {
			return l
		}
	}

	return nil
}

// compileBreak compiles a break statement. This is a branch whose destination
// is fixed up when the enclosing loop finishes compiling; the fixup address is
// added to the target loop's breaks list.
//
// An optional label after "break" (e.g. "break outer") names a specific
// enclosing loop to break out of. Without a label the innermost loop is used.
func (c *Compiler) compileBreak() error {
	if c.loops == nil {
		return c.compileError(errors.ErrInvalidLoopControl)
	}

	targetLoop := c.loops

	// If the next token is an identifier (on the same line, so no synthetic
	// semicolon precedes it), treat it as a loop label.
	if next := c.t.Peek(1); next.IsIdentifier() && !next.IsReserved(c.flags.extensionsEnabled) {
		label := c.t.Next().Spelling()
		targetLoop = c.findLoop(label)

		if targetLoop == nil {
			return c.compileError(errors.ErrUnknownLabel, label)
		}
	}

	fixAddr := c.b.Mark()

	c.b.Emit(bytecode.Branch, 0)
	
	targetLoop.breaks = append(targetLoop.breaks, fixAddr)

	return nil
}

// compileContinue compiles a continue statement. This is a branch whose
// destination is fixed up when the enclosing loop finishes compiling; the
// fixup address is added to the target loop's continues list.
//
// An optional label after "continue" (e.g. "continue outer") names a specific
// enclosing loop whose iteration to continue. Without a label the innermost
// loop is used.
func (c *Compiler) compileContinue() error {
	if c.loops == nil {
		return c.compileError(errors.ErrInvalidLoopControl)
	}

	targetLoop := c.loops

	if next := c.t.Peek(1); next.IsIdentifier() && !next.IsReserved(c.flags.extensionsEnabled) {
		label := c.t.Next().Spelling()
		targetLoop = c.findLoop(label)

		if targetLoop == nil {
			return c.compileError(errors.ErrUnknownLabel, label)
		}
	}

	targetLoop.continues = append(targetLoop.continues, c.b.Mark())

	c.b.Emit(bytecode.Branch, 0)

	return nil
}

// Generate a unique synthetic variable name, using a string value
// as a component of the name. This is used to convert a range variable
// of "_" to a unique hidden name, for example.
func generateIndexName(descriptor string) string {
	indexNameLock.Lock()

	indexName := fmt.Sprintf("$%s%d", descriptor, indexNameCounter)
	indexNameCounter++

	indexNameLock.Unlock()

	return indexName
}
