package compiler

import (
	"github.com/tucats/ego/bytecode"
)

// Expression is the public entry point for compiling a single expression. It
// returns the generated bytecode as a separate, independent object rather than
// appending it directly to the compiler's main stream. This is useful when the
// caller needs to inspect, reorder, or conditionally emit the code — for
// example, the for-loop compiler compiles the initializer, condition, and
// increment clauses as separate bytecode objects so it can lay them out in the
// correct order in the final loop structure.
//
// Internally the function delegates to conditional(), which sits at the top of
// the operator-precedence grammar:
//
//	conditional         → logicalOr (? logicalOr : logicalOr)?
//	logicalOr           → logicalAnd (|| logicalAnd)*
//	logicalAnd          → relations  (&& relations)*
//	relations           → addSubtract (== != < <= > >= addSubtract)*
//	addSubtract         → multiplyDivide (+ - | << >> multiplyDivide)*
//	multiplyDivide      → unary (* / % ^ & unary)*
//	unary               → (- | !) unary | functionOrReference
//	funcOrReference     → reference (argList)?
//	reference           → atom (. member | [index] | (args) )*
//	atom                → literal | identifier | ( expr ) | …
//
// When reportUsageErrors is true (the normal case) the function will return an
// error if the expression references a variable that has not been declared in
// any visible scope. Pass false when you only want to test whether a token
// sequence *could* parse as an expression without actually caring about
// symbol resolution.
func (c *Compiler) Expression(reportUsageErrors bool) (*bytecode.ByteCode, error) {
	// Expressions are compiled using a temporary clone of the compiler so that
	// the token-stream position and flag state changes made during expression
	// parsing are isolated. If parsing succeeds we adopt those changes; if it
	// fails we leave the parent compiler untouched.
	cx := c.Clone("expression eval")

	err := cx.conditional()
	if err == nil {
		// The clone advanced the token pointer and may have updated flags and
		// the scope stack. Propagate those changes back to the parent.
		c.t = cx.t
		c.flags = cx.flags
		c.scopes = cx.scopes

		if reportUsageErrors {
			// Close() finalizes the clone's bytecode and returns it.
			return cx.Close()
		}

		// When usage errors are suppressed we return the parent's (empty)
		// bytecode — the caller just wanted to know if parsing would succeed.
		return c.b, nil
	}

	return nil, err
}

// emitExpression is a convenience wrapper around Expression that immediately
// appends the compiled expression bytecode to the compiler's main output
// stream. Most statement compilers use this when they want the expression
// result on the runtime stack and don't need to hold the bytecode separately.
func (c *Compiler) emitExpression() error {
	bc, err := c.Expression(true)
	if err != nil {
		return err
	}

	c.b.Append(bc)

	return nil
}
