package compiler

import (
	"github.com/tucats/ego/bytecode"
	"github.com/tucats/ego/errors"
	"github.com/tucats/ego/tokenizer"
)

// compileIf compiles an if/else conditional statement. The "if" keyword has
// already been consumed by the caller.
//
// Ego supports the same two-clause form as Go:
//
//	if initStmt; condition { body } else { alt }
//
// where "initStmt;" is optional. When present, a new scope is pushed so that
// the variable declared in initStmt is only visible inside the if statement.
//
// The generated bytecode uses conditional branch instructions:
//   - BranchFalse jumps over the "true" body when the condition is false.
//   - An unconditional Branch jumps over the "false" (else) body after the
//     "true" body completes, so only one branch is ever taken.
//
// Both branch targets are recorded as fixup addresses (b1, b2) and resolved
// after the respective blocks have been compiled.
func (c *Compiler) compileIf() error {
	if c.t.AnyNext(tokenizer.SemicolonToken, tokenizer.EndOfTokens) {
		return c.compileError(errors.ErrMissingExpression)
	}

	conditionalAssignment := false

	// Check for the optional "initStmt;" prefix. isAssignmentTarget() peeks
	// ahead to see if what follows looks like an assignment statement.
	if c.isAssignmentTarget() {
		// The init statement lives in its own scope so that variables it
		// declares do not leak into the surrounding code.
		c.b.Emit(bytecode.PushScope)

		if err := c.compileAssignment(); err != nil {
			return err
		}

		// The init statement and the condition must be separated by ";".
		if !c.t.IsNext(tokenizer.SemicolonToken) {
			return c.compileError(errors.ErrMissingSemicolon)
		}

		conditionalAssignment = true
	}

	// Compile the boolean condition expression. Its result is left on the stack.
	if err := c.emitExpression(); err != nil {
		return err
	}

	// b1 is the address of the BranchFalse instruction. We don't know the
	// target yet, so use a placeholder of 0.
	b1 := c.b.Mark()
	c.b.Emit(bytecode.BranchFalse, 0)

	// Compile the "true" body — requires a block enclosed in "{}".
	if err := c.compileRequiredBlock(false); err != nil {
		return err
	}

	if c.t.IsNext(tokenizer.ElseToken) {
		// b2 marks the unconditional Branch that skips the else body after
		// the true body has finished executing.
		b2 := c.b.Mark()
		c.b.Emit(bytecode.Branch, 0)

		// Now we know where the else body starts — patch the BranchFalse.
		_ = c.b.SetAddressHere(b1)

		// "else if …" chains recursively without an extra block level.
		if c.t.IsNext(tokenizer.IfToken) {
			if err := c.compileIf(); err != nil {
				return err
			}
		} else {
			if err := c.compileRequiredBlock(false); err != nil {
				return err
			}
		}

		// Patch the Branch so it jumps past the else body.
		_ = c.b.SetAddressHere(b2)
	} else {
		// No else clause — the BranchFalse simply jumps here (past the body).
		_ = c.b.SetAddressHere(b1)
	}

	// If there was an init statement, discard the scope that was created for it.
	if conditionalAssignment {
		c.b.Emit(bytecode.PopScope)
	}

	return nil
}
