package class

import (
	"github.com/tucats/ego/internal/cli/cli"
	"github.com/tucats/ego/internal/commands"
	"github.com/tucats/ego/internal/defs"
)

// TableGrammar specifies the command line options for the "tables" Ego command.
var TableGrammar = []cli.Option{
	{
		LongName:      "sql",
		Description:   "ego.table.sql",
		OptionType:    cli.Subcommand,
		Action:        commands.TableSQL,
		ExpectedParms: defs.VariableParameterCount,
		ParmDesc:      "parm.sql.text",
		Value: []cli.Option{
			{
				LongName:    defs.DSNOption,
				ShortName:   "d",
				Aliases:     []string{"ds", "datasource"},
				Description: "dsn",
				OptionType:  cli.StringType,
			},
			{
				LongName:    "sql-file",
				ShortName:   "f",
				Aliases:     []string{"file"},
				Description: "sql.file",
				OptionType:  cli.StringType,
			},
			{
				LongName:    "row-ids",
				ShortName:   "i",
				Aliases:     []string{"ids"},
				Description: "sql.row.ids",
				OptionType:  cli.BooleanType,
			},
			{
				LongName:    "row-numbers",
				ShortName:   "n",
				Aliases:     []string{"row-number", "row"},
				Description: "sql.row.numbers",
				OptionType:  cli.BooleanType,
			},
		},
	},
	{
		LongName:      "permissions",
		Aliases:       []string{"perms"},
		Description:   "ego.table.permissions",
		OptionType:    cli.Subcommand,
		Action:        commands.TablePermissions,
		ExpectedParms: 0,
		Value: []cli.Option{
			{
				LongName:    "user",
				ShortName:   "u",
				Description: "table.permissions.user",
				OptionType:  cli.StringType,
			},
		},
	},
	{
		LongName:      "show-permission",
		Aliases:       []string{"permission", "perm"},
		Description:   "ego.table.permission",
		OptionType:    cli.Subcommand,
		Action:        commands.TableShowPermission,
		ExpectedParms: 1,
		ParmDesc:      "parm.table.name",
		Value: []cli.Option{
			{
				LongName:    "user",
				ShortName:   "u",
				Description: "table.permission.user",
				OptionType:  cli.StringType,
			},
		},
	},
	{
		LongName:      defs.GrantOption,
		Aliases:       []string{"permission"},
		Description:   "ego.table.grant",
		OptionType:    cli.Subcommand,
		Action:        commands.TableGrant,
		ExpectedParms: 1,
		ParmDesc:      "parm.table.name",
		Value: []cli.Option{
			{
				LongName:    "permission",
				Aliases:     []string{"permission", "permissions", "perms", "perm"},
				ShortName:   "p",
				Description: "table.grant.permission",
				OptionType:  cli.StringListType,
				Required:    true,
				Prompts:     []string{"table.permissions"},
			},
			{
				LongName:    "user",
				ShortName:   "u",
				Description: "table.grant.user",
				OptionType:  cli.StringType,
			},
		},
	},
	{
		LongName:      "list",
		Description:   "ego.table.list",
		OptionType:    cli.Subcommand,
		Action:        commands.TableList,
		ExpectedParms: -1,
		ParmDesc:      "DSN",
		Value: []cli.Option{
			{
				LongName:    defs.DSNOption,
				ShortName:   "d",
				Aliases:     []string{"ds", "datasource"},
				Description: "dsn",
				OptionType:  cli.StringType,
			},
			{
				LongName:    "limit",
				Aliases:     []string{"count"},
				Description: "limit",
				OptionType:  cli.IntType,
			},
			{
				LongName:    "start",
				Aliases:     []string{"offset"},
				Description: "start",
				OptionType:  cli.IntType,
			},
			{
				LongName:    "no-row-counts",
				Description: "table.list.no.row.counts",
				OptionType:  cli.BooleanType,
			},
		},
	},
	{
		LongName:      "show-table",
		Aliases:       []string{"show", "metadata", "columns"},
		Description:   "ego.table.show",
		OptionType:    cli.Subcommand,
		Action:        commands.TableShow,
		ExpectedParms: 1,
		ParmDesc:      "parm.table.name",
		Value: []cli.Option{
			{
				LongName:    defs.DSNOption,
				ShortName:   "d",
				Aliases:     []string{"ds", "datasource"},
				Description: "dsn",
				OptionType:  cli.StringType,
			},
			{
				LongName:    "row-id",
				ShortName:   "i",
				Aliases:     []string{"rowid"},
				Description: "sql.row.ids",
				OptionType:  cli.BooleanType,
			},
		},
	},
	{
		LongName:      "drop",
		Description:   "ego.table.drop",
		OptionType:    cli.Subcommand,
		Action:        commands.TableDrop,
		ExpectedParms: defs.VariableParameterCount,
		ParmDesc:      "table-name [table-name...]",
		Value: []cli.Option{
			{
				LongName:    defs.DSNOption,
				ShortName:   "d",
				Aliases:     []string{"ds", "datasource"},
				Description: "dsn",
				OptionType:  cli.StringType,
			},
		},
	},
	{
		LongName:      "read",
		Aliases:       []string{"select", "print", "get", "show-contents", "contents"},
		Description:   "ego.table.read",
		OptionType:    cli.Subcommand,
		Action:        commands.TableContents,
		ExpectedParms: 1,
		Value: []cli.Option{
			{
				LongName:    defs.DSNOption,
				ShortName:   "d",
				Aliases:     []string{"ds", "datasource"},
				Description: "dsn",
				OptionType:  cli.StringType,
			},
			{
				LongName:    "row-ids",
				ShortName:   "i",
				Aliases:     []string{"ids"},
				Description: "table.read.row.ids",
				OptionType:  cli.BooleanType,
			},
			{
				LongName:    "row-numbers",
				ShortName:   "n",
				Aliases:     []string{"row-number", "row"},
				Description: "table.read.row.numbers",
				OptionType:  cli.BooleanType,
			},
			{
				LongName:    "columns",
				ShortName:   "c",
				Aliases:     []string{"column"},
				Description: "table.read.columns",
				OptionType:  cli.StringListType,
			},

			{
				LongName:    "order-by",
				ShortName:   "o",
				Aliases:     []string{"sort", "order"},
				Description: "table.read.order.by",
				OptionType:  cli.StringListType,
			},
			{
				LongName:    "filter",
				ShortName:   "f",
				Aliases:     []string{"where"},
				Description: "filter",
				OptionType:  cli.StringListType,
			},
			{
				LongName:    "limit",
				Aliases:     []string{"count"},
				Description: "limit",
				OptionType:  cli.IntType,
			},
			{
				LongName:    "start",
				Aliases:     []string{"offset"},
				Description: "start",
				OptionType:  cli.IntType,
			},
		},
	},
	{
		LongName:      "delete",
		Description:   "ego.table.delete",
		OptionType:    cli.Subcommand,
		Action:        commands.TableDelete,
		ExpectedParms: 1,
		Value: []cli.Option{
			{
				LongName:    defs.DSNOption,
				ShortName:   "d",
				Aliases:     []string{"ds", "datasource"},
				Description: "dsn",
				OptionType:  cli.StringType,
			},
			{
				LongName:    "filter",
				ShortName:   "f",
				Aliases:     []string{"where"},
				Description: "table.delete.filter",
				OptionType:  cli.StringListType,
			},
		},
	},
	{
		LongName:      "insert",
		Aliases:       []string{"write", "append"},
		Description:   "ego.table.insert",
		OptionType:    cli.Subcommand,
		Action:        commands.TableInsert,
		ExpectedParms: defs.VariableParameterCount,
		ParmDesc:      "parm.table.insert",
		Value: []cli.Option{
			{
				LongName:    defs.DSNOption,
				ShortName:   "d",
				Aliases:     []string{"ds", "datasource"},
				Description: "dsn",
				OptionType:  cli.StringType,
			},
			{
				LongName:    "file",
				Aliases:     []string{"json-file", "json"},
				ShortName:   "f",
				Description: "table.insert.file",
				OptionType:  cli.StringListType,
			},
		},
	},
	{
		LongName:      "update",
		Description:   "ego.table.update",
		OptionType:    cli.Subcommand,
		Action:        commands.TableUpdate,
		ExpectedParms: defs.VariableParameterCount,
		ParmDesc:      "parm.table.update",
		Value: []cli.Option{
			{
				LongName:    defs.DSNOption,
				ShortName:   "d",
				Aliases:     []string{"ds", "datasource"},
				Description: "dsn",
				OptionType:  cli.StringType,
			},
			{
				LongName:    "filter",
				ShortName:   "f",
				Aliases:     []string{"where"},
				Description: "table.update.filter",
				OptionType:  cli.StringListType,
			},
		},
	},
	{
		LongName:      "create",
		Description:   "ego.table.create",
		OptionType:    cli.Subcommand,
		Action:        commands.TableCreate,
		ExpectedParms: defs.VariableParameterCount,
		ParmDesc:      "parm.table.create",
		Value: []cli.Option{
			{
				LongName:    defs.DSNOption,
				ShortName:   "d",
				Aliases:     []string{"ds", "datasource"},
				Description: "dsn",
				OptionType:  cli.StringType,
			},
			{
				LongName:    "file",
				Aliases:     []string{"json-file", "json"},
				ShortName:   "f",
				Description: "table.create.file",
				OptionType:  cli.StringListType,
			},
		},
	},
}
