package services

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/tucats/ego/app-cli/settings"
	"github.com/tucats/ego/app-cli/ui"
	"github.com/tucats/ego/bytecode"
	"github.com/tucats/ego/compiler"
	"github.com/tucats/ego/data"
	"github.com/tucats/ego/debugger"
	"github.com/tucats/ego/defs"
	"github.com/tucats/ego/errors"
	egohttp "github.com/tucats/ego/runtime/http"
	"github.com/tucats/ego/server/auth"
	"github.com/tucats/ego/server/server"
	"github.com/tucats/ego/symbols"
	"github.com/tucats/ego/util"
)

var serviceConcurrancy sync.Mutex

// ServiceHandler is the rest handler for services written
// in Ego. It loads and compiles the service code, and
// then runs it with a context specific to each request.
func ServiceHandler(session *server.Session, w http.ResponseWriter, r *http.Request) int {
	if settings.GetBool(defs.ChildServicesSetting) {
		return callChildServices(session, w, r)
	}

	// Initialize the service cache if it is not already set up.
	setupServiceCache()

	// Do some housekeeping. Initialize the status and session
	// id information, and log that we're here.
	status := http.StatusOK
	requestor := additionalServerRequestLogging(r, session.ID)

	// Set up the server symbol table for this service call.
	symbolTable := setupServerSymbols(r, session, requestor)

	// Get the query parameters and store as an Ego map value.
	parameters := map[string]interface{}{}

	for k, v := range r.URL.Query() {
		values := make([]interface{}, 0)
		for _, vs := range v {
			values = append(values, vs)
		}

		parameters[k] = data.NewArrayFromInterfaces(data.InterfaceType, values...)
	}

	symbolTable.SetAlways(defs.ParametersVariable, data.NewMapFromMap(parameters))

	// Put all the headers where they can be accessed as well. The authorization
	// header is omitted.
	headers := map[string]interface{}{}
	isJSON := false

	for name, values := range r.Header {
		if strings.ToLower(name) != "authorization" {
			valueList := []interface{}{}

			for _, value := range values {
				valueList = append(valueList, value)

				if strings.EqualFold(name, "Accept") && strings.Contains(value, defs.JSONMediaType) {
					isJSON = true
				}
			}

			headers[name] = valueList
		}
	}

	symbolTable.SetAlways(defs.HeadersMapVariable, data.NewMapFromMap(headers))
	symbolTable.SetAlways(defs.JSONMediaVariable, isJSON)

	// Determine path and endpoint values for this request.
	path := r.URL.Path
	if path[:1] == "/" {
		path = path[1:]
	}

	// The endpoint might have trailing path stuff; if so we need to find
	// the part of the path that is the actual endpoint, so we can locate
	// the service program. Also, store the full path, the endpoint,
	// and any suffix that the service might want to process.
	endpoint := session.Path
	pathSuffix := ""

	if len(endpoint) < len(path) {
		pathSuffix = path[len(endpoint):]
	}

	if pathSuffix != "" {
		pathSuffix = "/" + pathSuffix
	}

	// Create symbols describing the URL we were given for this service call.
	// Also, now is a good time to add the functions and other builtin info
	// needed for a rest handler.
	symbolTable.SetAlways("_url", r.URL.String())
	symbolTable.SetAlways("_path_endpoint", endpoint)
	symbolTable.SetAlways("_path", "/"+path)
	symbolTable.SetAlways("_path_suffix", pathSuffix)
	symbolTable.SetAlways("authenticated", auth.Authenticated)
	symbolTable.SetAlways("permission", auth.Permission)
	symbolTable.SetAlways("setuser", auth.SetUser)
	symbolTable.SetAlways("getuser", auth.GetUser)
	symbolTable.SetAlways("deleteuser", auth.DeleteUser)
	symbolTable.SetAlways(defs.RestResponseName, nil)

	// Construct an Ego ResponseWriter object for this service call.
	writer := data.NewStructOfTypeFromMap(egohttp.ResponseWriterType, map[string]interface{}{
		"_writer": w,
		"_size":   0})

	symbolTable.SetAlways("_responseWriter", writer)

	// If there are URLParts (from an @endpoint directive) then store them
	// as a struct in the local storage so the service can access them easily.
	if session.URLParts != nil {
		m := data.NewMapFromMap(session.URLParts)
		symbolTable.SetAlways("_urlparts", m)
	}

	// If there was a decomposed URL generated by the router to this handler,
	// make the symbols present in the symbol table as well.
	msg := strings.Builder{}

	for k, v := range session.URLParts {
		if msg.Len() > 0 {
			msg.WriteString(", ")
		}

		msg.WriteString(fmt.Sprintf("%s = %v", k, v))
		symbolTable.SetAlways(k, v)
	}

	ui.Log(ui.RestLogger, "rest.url.parts", ui.A{
		"session":  session.ID,
		"path":     path,
		"urlparts": session.URLParts})

	// Add the runtime packages to the symbol table.
	serviceConcurrancy.Lock()

	comp := compiler.New("auto-import")
	_ = comp.AutoImport(false, symbolTable)

	serviceConcurrancy.Unlock()

	// Now that we know the actual endpoint, see if this is the endpoint we are debugging?
	debug := false

	if b, ok := symbols.RootSymbolTable.Get(defs.DebugServicePathVariable); ok {
		debugPath := data.String(b)
		if debugPath == "/" {
			debug = true
		} else {
			debug = strings.EqualFold(data.String(b), endpoint)
		}
	}

	// Time to either compile a service, or re-use one from the cache. The
	// following items will be set to describe the service we run. If this
	// fails, it means a compiler or file system error, so report that.
	serviceCode, tokens, err := getCachedService(session.ID, endpoint, debug, session.Filename, symbolTable)
	if err != nil {
		ui.Log(ui.ServicesLogger, "services.compile.error", ui.A{
			"session": session.ID,
			"error":   err.Error()})

		status = http.StatusBadRequest
		w.WriteHeader(status)

		if isJSON {
			resp := defs.RestStatusResponse{
				ServerInfo: util.MakeServerInfo(session.ID),
				Status:     status,
				Message:    err.Error(),
			}

			b, _ := json.Marshal(resp)
			_, _ = w.Write(b)
			session.ResponseLength += len(b)

			if ui.IsActive(ui.RestLogger) {
				ui.WriteLog(ui.RestLogger, "rest.response.payload", ui.A{
					"session": session.ID,
					"body":    string(b)})
			}
		} else {
			text := err.Error()
			_, _ = w.Write([]byte(text))
			session.ResponseLength += len(text)
		}

		return status
	}

	// The symbol table we have now represents the clean compilation. Make a child of it that
	// will contain the (discardable) context for running the service.
	symbolTable = symbols.NewChildSymbolTable("runtime "+symbolTable.Name, symbolTable)
	ui.Log(ui.ServicesLogger, "services.using.symbols", ui.A{
		"session":  session.ID,
		"endpoint": endpoint,
		"table":    symbolTable.Parent().Name})

	// If there is a request ID, store it in the symbol table for use by running services.
	// Copy the authentication info in the session structure to the symbol table for use
	// by running services.
	setAuthSymbols(session, symbolTable)

	// Get the body of the request as a string, and store in the symbol table.
	byteBuffer := new(bytes.Buffer)
	_, _ = byteBuffer.ReadFrom(r.Body)

	symbolTable.SetAlways("_body", byteBuffer.String())

	// Add the standard non-package function into this symbol table
	_ = compiler.AddStandard(symbolTable)

	// If enabled, dump out the symbol table to the log. Omit the packages
	// from the table (they are the default packages). This is only done
	// when symbol table logging is enabled.
	if ui.IsActive(ui.SymbolLogger) {
		symbolTable.Log(session.ID, ui.ServicesLogger, true)
	}

	// Run the service code in a new context created for this session. If debug mode is enabled,
	// use the debugger to run the code, else just run from the context. In either case, if the
	// result is the STOP return code, remap that to nil (no error).
	ctx := bytecode.NewContext(symbolTable, serviceCode).SetDebug(debug)
	ctx.EnableConsoleOutput(true)

	if debug {
		ui.Log(ui.ServicesLogger, "services.debug.start", ui.A{
			"session":  session.ID,
			"method":   r.Method,
			"endpoint": r.URL.Path})

		ctx.SetTokenizer(tokens)

		err = debugger.Run(ctx.SetTokenizer(tokens))

		ui.Log(ui.ServicesLogger, "services.debug.end", ui.A{
			"session":  session.ID,
			"method":   r.Method,
			"endpoint": r.URL.Path,
			"error":    err.Error()})
	} else {
		startTime := time.Now()

		ui.Log(ui.ServicesLogger, "services.run", ui.A{
			"session": session.ID,
			"name":    ctx.GetName()})

		err = ctx.Run()
		elapsed := time.Since(startTime)

		ui.Log(ui.ServicesLogger, "services.elapsed", ui.A{
			"session":  session.ID,
			"name":     ctx.GetName(),
			"duration": elapsed.String()})
	}

	if errors.Equals(err, errors.ErrStop) {
		err = nil
	} else if errors.Equals(err, errors.ErrExit) {
		msg := err.Error()
		if e, ok := err.(*errors.Error); ok {
			msg = fmt.Sprintf(", %s", e.GetContext())
		}

		return util.ErrorResponse(w, session.ID, "Service aborted"+msg, http.StatusServiceUnavailable)
	}

	// Runtime error? If so, delete us from the cache if present. This may let the administrator
	// fix errors in the code and just re-run without having to flush the cache or restart the
	// server.
	if err != nil {
		ui.Log(ui.ServicesLogger, "services.run.error", ui.A{
			"session": session.ID,
			"error":   err.Error()})

		// Because of the error, remove from the cache.
		serviceCacheMutex.Lock()
		delete(ServiceCache, endpoint)
		serviceCacheMutex.Unlock()
	}

	if err != nil {
		return util.ErrorResponse(w, session.ID, "Error: "+err.Error(), http.StatusInternalServerError)
	}

	// No errors, so let's figure out how to format the response to the calling cliient.
	if isJSON {
		w.Header().Add(defs.ContentTypeHeader, defs.JSONMediaType)
	}

	w.WriteHeader(status)

	// @tomcole need to figure out how much was written to the reponseWriter.
	size := 0 /* Length of response? */
	session.ResponseLength += size

	// Last thing, if this service is cached but doesn't have a symbol table in
	// the cache, give our current set to the cached item. This is the parent of the
	// active table (the active table has the runtime results of this particular execution).
	updateCachedServiceSymbols(session.ID, endpoint, symbolTable.Parent())

	// If the result status was indicating that the service is unavailable, let's start
	// a shutdown to make this a true statement. We always sleep for one second to allow
	// the response to clear back to the caller. By locking the service cache before we
	// do this, we prevent any additional services from starting.
	if status == http.StatusServiceUnavailable {
		serviceCacheMutex.Lock()
		go func() {
			time.Sleep(1 * time.Second)
			ui.Log(ui.ServerLogger, "server.shutdown", nil)
			os.Exit(0)
		}()
	}

	return status
}

// Define the root symbol table for this REST request.
func setupServerSymbols(r *http.Request, session *server.Session, requestor string) *symbols.SymbolTable {
	// Create a new symbol table for this request. The symbol table name is formed from the
	// method and URL path.
	symbolTable := symbols.NewRootSymbolTable(r.Method + " " + data.SanitizeName(r.URL.Path))

	// Define information we know about our running session and the caller, independent of
	// the service being invoked.
	symbolTable.SetAlways(defs.PidVariable, os.Getpid())
	symbolTable.SetAlways(defs.InstanceUUIDVariable, defs.InstanceID)
	symbolTable.SetAlways(defs.SessionVariable, session.ID)
	symbolTable.SetAlways(defs.MethodVariable, r.Method)
	symbolTable.SetAlways(defs.ModeVariable, "server")
	symbolTable.SetAlways(defs.VersionNameVariable, server.Version)
	symbolTable.SetAlways(defs.StartTimeVariable, server.StartTime)
	symbolTable.SetAlways(defs.RequestorVariable, requestor)

	symbolTable.Root().SetAlways(defs.ExtensionsVariable,
		settings.GetBool(defs.ExtensionsEnabledSetting))

	// Make sure we have recorded the extensions status and type check setting.
	if staticTypes := settings.GetUsingList(defs.StaticTypesSetting,
		defs.Strict,
		defs.Relaxed,
		defs.Dynamic,
	) - 1; staticTypes < defs.StrictTypeEnforcement {
		symbolTable.SetAlways(defs.TypeCheckingVariable, defs.NoTypeEnforcement)
	} else {
		symbolTable.SetAlways(defs.TypeCheckingVariable, staticTypes)
	}

	return symbolTable
}

func parameterString(r *http.Request) string {
	m := r.URL.Query()
	result := strings.Builder{}

	for k, v := range m {
		if result.Len() == 0 {
			result.WriteRune('?')
		} else {
			result.WriteRune('&')
		}

		result.WriteString(k)

		if len(v) > 0 {
			result.WriteRune('=')

			for n, value := range v {
				if n > 0 {
					result.WriteRune(',')
				}

				result.WriteString(value)
			}
		}
	}

	return result.String()
}
