// Package debugger contains the interactive runtime debugger for executing
// compiled Ego programs.
//
// # Overview
//
// When a bytecode stream is to be run under the debugger, the caller passes a
// bytecode.Context to one of two entry points:
//
//   - [Run] — interactive mode. Reads commands from stdin and writes output to
//     stdout, exactly as the original CLI debugger did. The call blocks until
//     the program finishes.
//
//   - [Resume] — API mode. Each call delivers one command string to the running
//     debugger and returns a [Response] containing all output generated up to
//     the next input prompt (or program termination). The first call should pass
//     an empty command; subsequent calls pass the command entered by the user.
//     When [Response.Done] is true the session has ended.
//
//   - [Close] — tears down an API-mode session that is no longer needed (e.g.
//     when a REST client disconnects mid-session).
//
// # How it works
//
// The debugger detects errors.ErrSignalDebugger signals returned by the running
// bytecode stream. This signal is generated by the AtLine opcode when the
// context is in debug mode, meaning control is offered to the debugger at the
// start of every source line.
//
// When given control, the debugger evaluates what action, if any, is needed:
//
//   - If the code has no breakpoints active and is not in single-step mode the
//     debugger takes no action and the next line executes immediately.
//
//   - If a breakpoint condition is met, or single-step mode is active, the
//     debugger enters interactive mode: it prints the current source location,
//     reads a command, and acts on it.
//
// # I/O model
//
// All debugger output (including prompts, source listings, symbol dumps, etc.)
// is written through a [session] which abstracts the output destination.  In
// interactive mode the session writes directly to stdout; in API mode it
// writes to a channel that [Resume] drains between calls.  All input is
// similarly read through the session: interactive mode uses the readline-based
// console reader, while API mode blocks on the input channel until [Resume]
// delivers the next command.
//
// # API-mode usage example
//
//	// First call: no input yet — run to the first debug stop.
//	resp := debugger.Resume(ctx, "")
//	for !resp.Done {
//	    // Display resp.Output to the user, then show resp.Prompt and get input.
//	    userCmd := askUser(resp.Prompt)
//	    resp = debugger.Resume(ctx, userCmd)
//	}
//	if resp.Err != nil {
//	    log.Println("debugger error:", resp.Err)
//	}
//
// # Available commands
//
// In interactive mode, the user can enter the following commands. All commands
// are case-sensitive.
//
//   - break at [module:]line — set a line breakpoint
//   - break when expression — set a conditional breakpoint
//   - break clear at [module:]line — remove a line breakpoint
//   - break clear when expression — remove a conditional breakpoint
//   - break save ["file"] — save breakpoints to a JSON file
//   - break load ["file"] — load breakpoints from a JSON file
//   - continue (or go) — resume execution without single-step
//   - exit — stop the program
//   - help — show this command reference
//   - print expression — evaluate and print an expression
//   - set variable = expression — assign a value to a variable
//   - call expression — call a function (with trace)
//   - show breaks — list current breakpoints
//   - show calls [n] — show the call stack (top n frames)
//   - show line — show the current source line
//   - show scope — show symbol-table scope chain
//   - show source [start[:end]] — list source lines
//   - show symbols — dump the current symbol table
//   - step [into] — execute one source line; step into calls
//   - step over — execute one source line; step over calls
//   - step return — run until the current function returns
package debugger
